// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteAPIV3MachinesRfqdnReader is a Reader for the DeleteAPIV3MachinesRfqdn structure.
type DeleteAPIV3MachinesRfqdnReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIV3MachinesRfqdnReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteAPIV3MachinesRfqdnNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAPIV3MachinesRfqdnNoContent creates a DeleteAPIV3MachinesRfqdnNoContent with default headers values
func NewDeleteAPIV3MachinesRfqdnNoContent() *DeleteAPIV3MachinesRfqdnNoContent {
	return &DeleteAPIV3MachinesRfqdnNoContent{}
}

/*DeleteAPIV3MachinesRfqdnNoContent handles this case with default header values.

Delete a machine
*/
type DeleteAPIV3MachinesRfqdnNoContent struct {
}

func (o *DeleteAPIV3MachinesRfqdnNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/machines/{rfqdn}][%d] deleteApiV3MachinesRfqdnNoContent ", 204)
}

func (o *DeleteAPIV3MachinesRfqdnNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
