// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// GetAPIV3SwitchesFqdnPortsReader is a Reader for the GetAPIV3SwitchesFqdnPorts structure.
type GetAPIV3SwitchesFqdnPortsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3SwitchesFqdnPortsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV3SwitchesFqdnPortsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV3SwitchesFqdnPortsOK creates a GetAPIV3SwitchesFqdnPortsOK with default headers values
func NewGetAPIV3SwitchesFqdnPortsOK() *GetAPIV3SwitchesFqdnPortsOK {
	return &GetAPIV3SwitchesFqdnPortsOK{}
}

/*GetAPIV3SwitchesFqdnPortsOK handles this case with default header values.

Return a list of switch ports
*/
type GetAPIV3SwitchesFqdnPortsOK struct {
	Payload models.GetAPIV3SwitchesFqdnPortsOKBody
}

func (o *GetAPIV3SwitchesFqdnPortsOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/switches/{fqdn}/ports][%d] getApiV3SwitchesFqdnPortsOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3SwitchesFqdnPortsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
