// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// GetAPIV3CloudProvidersReader is a Reader for the GetAPIV3CloudProviders structure.
type GetAPIV3CloudProvidersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3CloudProvidersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV3CloudProvidersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV3CloudProvidersOK creates a GetAPIV3CloudProvidersOK with default headers values
func NewGetAPIV3CloudProvidersOK() *GetAPIV3CloudProvidersOK {
	return &GetAPIV3CloudProvidersOK{}
}

/*GetAPIV3CloudProvidersOK handles this case with default header values.

Return a list of cloud providers, possibly filtered
*/
type GetAPIV3CloudProvidersOK struct {
	Payload models.GetAPIV3CloudProvidersOKBody
}

func (o *GetAPIV3CloudProvidersOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/cloud_providers][%d] getApiV3CloudProvidersOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3CloudProvidersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
