// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// GetAPIV3CloudProvidersRnameReader is a Reader for the GetAPIV3CloudProvidersRname structure.
type GetAPIV3CloudProvidersRnameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3CloudProvidersRnameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV3CloudProvidersRnameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV3CloudProvidersRnameOK creates a GetAPIV3CloudProvidersRnameOK with default headers values
func NewGetAPIV3CloudProvidersRnameOK() *GetAPIV3CloudProvidersRnameOK {
	return &GetAPIV3CloudProvidersRnameOK{}
}

/*GetAPIV3CloudProvidersRnameOK handles this case with default header values.

Get cloud provider by name
*/
type GetAPIV3CloudProvidersRnameOK struct {
	Payload *models.CloudProvider
}

func (o *GetAPIV3CloudProvidersRnameOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/cloud_providers/{rname}][%d] getApiV3CloudProvidersRnameOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3CloudProvidersRnameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudProvider)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
