// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// GetAPIV3MachinesRfqdnNicsRnicReader is a Reader for the GetAPIV3MachinesRfqdnNicsRnic structure.
type GetAPIV3MachinesRfqdnNicsRnicReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3MachinesRfqdnNicsRnicReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV3MachinesRfqdnNicsRnicOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV3MachinesRfqdnNicsRnicOK creates a GetAPIV3MachinesRfqdnNicsRnicOK with default headers values
func NewGetAPIV3MachinesRfqdnNicsRnicOK() *GetAPIV3MachinesRfqdnNicsRnicOK {
	return &GetAPIV3MachinesRfqdnNicsRnicOK{}
}

/*GetAPIV3MachinesRfqdnNicsRnicOK handles this case with default header values.

Get a nic
*/
type GetAPIV3MachinesRfqdnNicsRnicOK struct {
	Payload *models.Nic
}

func (o *GetAPIV3MachinesRfqdnNicsRnicOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/machines/{rfqdn}/nics/{rnic}][%d] getApiV3MachinesRfqdnNicsRnicOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3MachinesRfqdnNicsRnicOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Nic)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
