// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// GetAPIV3MachinesRfqdnAttachmentsFingerprintReader is a Reader for the GetAPIV3MachinesRfqdnAttachmentsFingerprint structure.
type GetAPIV3MachinesRfqdnAttachmentsFingerprintReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3MachinesRfqdnAttachmentsFingerprintReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV3MachinesRfqdnAttachmentsFingerprintOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV3MachinesRfqdnAttachmentsFingerprintOK creates a GetAPIV3MachinesRfqdnAttachmentsFingerprintOK with default headers values
func NewGetAPIV3MachinesRfqdnAttachmentsFingerprintOK() *GetAPIV3MachinesRfqdnAttachmentsFingerprintOK {
	return &GetAPIV3MachinesRfqdnAttachmentsFingerprintOK{}
}

/*GetAPIV3MachinesRfqdnAttachmentsFingerprintOK handles this case with default header values.

Get an attachment
*/
type GetAPIV3MachinesRfqdnAttachmentsFingerprintOK struct {
	Payload *models.Attachment
}

func (o *GetAPIV3MachinesRfqdnAttachmentsFingerprintOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/machines/{rfqdn}/attachments/{fingerprint}][%d] getApiV3MachinesRfqdnAttachmentsFingerprintOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3MachinesRfqdnAttachmentsFingerprintOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Attachment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
