// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// GetAPIV3MachinesReader is a Reader for the GetAPIV3Machines structure.
type GetAPIV3MachinesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3MachinesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV3MachinesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV3MachinesOK creates a GetAPIV3MachinesOK with default headers values
func NewGetAPIV3MachinesOK() *GetAPIV3MachinesOK {
	return &GetAPIV3MachinesOK{}
}

/*GetAPIV3MachinesOK handles this case with default header values.

Return a list of machines, possibly filtered
*/
type GetAPIV3MachinesOK struct {
	Payload models.GetAPIV3MachinesOKBody
}

func (o *GetAPIV3MachinesOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/machines][%d] getApiV3MachinesOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3MachinesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
