// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// GetAPIV3MachinesRfqdnAttachmentsReader is a Reader for the GetAPIV3MachinesRfqdnAttachments structure.
type GetAPIV3MachinesRfqdnAttachmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3MachinesRfqdnAttachmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV3MachinesRfqdnAttachmentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV3MachinesRfqdnAttachmentsOK creates a GetAPIV3MachinesRfqdnAttachmentsOK with default headers values
func NewGetAPIV3MachinesRfqdnAttachmentsOK() *GetAPIV3MachinesRfqdnAttachmentsOK {
	return &GetAPIV3MachinesRfqdnAttachmentsOK{}
}

/*GetAPIV3MachinesRfqdnAttachmentsOK handles this case with default header values.

Get all attachments
*/
type GetAPIV3MachinesRfqdnAttachmentsOK struct {
	Payload models.GetAPIV3MachinesRfqdnAttachmentsOKBody
}

func (o *GetAPIV3MachinesRfqdnAttachmentsOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/machines/{rfqdn}/attachments][%d] getApiV3MachinesRfqdnAttachmentsOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3MachinesRfqdnAttachmentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
