// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAPIV3LocationsLevelsParams creates a new GetAPIV3LocationsLevelsParams object
// with the default values initialized.
func NewGetAPIV3LocationsLevelsParams() *GetAPIV3LocationsLevelsParams {

	return &GetAPIV3LocationsLevelsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV3LocationsLevelsParamsWithTimeout creates a new GetAPIV3LocationsLevelsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV3LocationsLevelsParamsWithTimeout(timeout time.Duration) *GetAPIV3LocationsLevelsParams {

	return &GetAPIV3LocationsLevelsParams{

		timeout: timeout,
	}
}

// NewGetAPIV3LocationsLevelsParamsWithContext creates a new GetAPIV3LocationsLevelsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV3LocationsLevelsParamsWithContext(ctx context.Context) *GetAPIV3LocationsLevelsParams {

	return &GetAPIV3LocationsLevelsParams{

		Context: ctx,
	}
}

// NewGetAPIV3LocationsLevelsParamsWithHTTPClient creates a new GetAPIV3LocationsLevelsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV3LocationsLevelsParamsWithHTTPClient(client *http.Client) *GetAPIV3LocationsLevelsParams {

	return &GetAPIV3LocationsLevelsParams{
		HTTPClient: client,
	}
}

/*GetAPIV3LocationsLevelsParams contains all the parameters to send to the API endpoint
for the get Api v3 locations levels operation typically these are written to a http.Request
*/
type GetAPIV3LocationsLevelsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get Api v3 locations levels params
func (o *GetAPIV3LocationsLevelsParams) WithTimeout(timeout time.Duration) *GetAPIV3LocationsLevelsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Api v3 locations levels params
func (o *GetAPIV3LocationsLevelsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Api v3 locations levels params
func (o *GetAPIV3LocationsLevelsParams) WithContext(ctx context.Context) *GetAPIV3LocationsLevelsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Api v3 locations levels params
func (o *GetAPIV3LocationsLevelsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get Api v3 locations levels params
func (o *GetAPIV3LocationsLevelsParams) WithHTTPClient(client *http.Client) *GetAPIV3LocationsLevelsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get Api v3 locations levels params
func (o *GetAPIV3LocationsLevelsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV3LocationsLevelsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
