// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAPIV3LocationsIDIDParams creates a new GetAPIV3LocationsIDIDParams object
// with the default values initialized.
func NewGetAPIV3LocationsIDIDParams() *GetAPIV3LocationsIDIDParams {
	var ()
	return &GetAPIV3LocationsIDIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV3LocationsIDIDParamsWithTimeout creates a new GetAPIV3LocationsIDIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV3LocationsIDIDParamsWithTimeout(timeout time.Duration) *GetAPIV3LocationsIDIDParams {
	var ()
	return &GetAPIV3LocationsIDIDParams{

		timeout: timeout,
	}
}

// NewGetAPIV3LocationsIDIDParamsWithContext creates a new GetAPIV3LocationsIDIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV3LocationsIDIDParamsWithContext(ctx context.Context) *GetAPIV3LocationsIDIDParams {
	var ()
	return &GetAPIV3LocationsIDIDParams{

		Context: ctx,
	}
}

// NewGetAPIV3LocationsIDIDParamsWithHTTPClient creates a new GetAPIV3LocationsIDIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV3LocationsIDIDParamsWithHTTPClient(client *http.Client) *GetAPIV3LocationsIDIDParams {
	var ()
	return &GetAPIV3LocationsIDIDParams{
		HTTPClient: client,
	}
}

/*GetAPIV3LocationsIDIDParams contains all the parameters to send to the API endpoint
for the get Api v3 locations Id Id operation typically these are written to a http.Request
*/
type GetAPIV3LocationsIDIDParams struct {

	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get Api v3 locations Id Id params
func (o *GetAPIV3LocationsIDIDParams) WithTimeout(timeout time.Duration) *GetAPIV3LocationsIDIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Api v3 locations Id Id params
func (o *GetAPIV3LocationsIDIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Api v3 locations Id Id params
func (o *GetAPIV3LocationsIDIDParams) WithContext(ctx context.Context) *GetAPIV3LocationsIDIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Api v3 locations Id Id params
func (o *GetAPIV3LocationsIDIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get Api v3 locations Id Id params
func (o *GetAPIV3LocationsIDIDParams) WithHTTPClient(client *http.Client) *GetAPIV3LocationsIDIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get Api v3 locations Id Id params
func (o *GetAPIV3LocationsIDIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get Api v3 locations Id Id params
func (o *GetAPIV3LocationsIDIDParams) WithID(id int32) *GetAPIV3LocationsIDIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get Api v3 locations Id Id params
func (o *GetAPIV3LocationsIDIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV3LocationsIDIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
