// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAPIV3SwitchesFqdnPortsNumberParams creates a new GetAPIV3SwitchesFqdnPortsNumberParams object
// with the default values initialized.
func NewGetAPIV3SwitchesFqdnPortsNumberParams() *GetAPIV3SwitchesFqdnPortsNumberParams {
	var ()
	return &GetAPIV3SwitchesFqdnPortsNumberParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV3SwitchesFqdnPortsNumberParamsWithTimeout creates a new GetAPIV3SwitchesFqdnPortsNumberParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV3SwitchesFqdnPortsNumberParamsWithTimeout(timeout time.Duration) *GetAPIV3SwitchesFqdnPortsNumberParams {
	var ()
	return &GetAPIV3SwitchesFqdnPortsNumberParams{

		timeout: timeout,
	}
}

// NewGetAPIV3SwitchesFqdnPortsNumberParamsWithContext creates a new GetAPIV3SwitchesFqdnPortsNumberParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV3SwitchesFqdnPortsNumberParamsWithContext(ctx context.Context) *GetAPIV3SwitchesFqdnPortsNumberParams {
	var ()
	return &GetAPIV3SwitchesFqdnPortsNumberParams{

		Context: ctx,
	}
}

// NewGetAPIV3SwitchesFqdnPortsNumberParamsWithHTTPClient creates a new GetAPIV3SwitchesFqdnPortsNumberParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV3SwitchesFqdnPortsNumberParamsWithHTTPClient(client *http.Client) *GetAPIV3SwitchesFqdnPortsNumberParams {
	var ()
	return &GetAPIV3SwitchesFqdnPortsNumberParams{
		HTTPClient: client,
	}
}

/*GetAPIV3SwitchesFqdnPortsNumberParams contains all the parameters to send to the API endpoint
for the get Api v3 switches fqdn ports number operation typically these are written to a http.Request
*/
type GetAPIV3SwitchesFqdnPortsNumberParams struct {

	/*Fqdn*/
	Fqdn string
	/*Number*/
	Number int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get Api v3 switches fqdn ports number params
func (o *GetAPIV3SwitchesFqdnPortsNumberParams) WithTimeout(timeout time.Duration) *GetAPIV3SwitchesFqdnPortsNumberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Api v3 switches fqdn ports number params
func (o *GetAPIV3SwitchesFqdnPortsNumberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Api v3 switches fqdn ports number params
func (o *GetAPIV3SwitchesFqdnPortsNumberParams) WithContext(ctx context.Context) *GetAPIV3SwitchesFqdnPortsNumberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Api v3 switches fqdn ports number params
func (o *GetAPIV3SwitchesFqdnPortsNumberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get Api v3 switches fqdn ports number params
func (o *GetAPIV3SwitchesFqdnPortsNumberParams) WithHTTPClient(client *http.Client) *GetAPIV3SwitchesFqdnPortsNumberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get Api v3 switches fqdn ports number params
func (o *GetAPIV3SwitchesFqdnPortsNumberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFqdn adds the fqdn to the get Api v3 switches fqdn ports number params
func (o *GetAPIV3SwitchesFqdnPortsNumberParams) WithFqdn(fqdn string) *GetAPIV3SwitchesFqdnPortsNumberParams {
	o.SetFqdn(fqdn)
	return o
}

// SetFqdn adds the fqdn to the get Api v3 switches fqdn ports number params
func (o *GetAPIV3SwitchesFqdnPortsNumberParams) SetFqdn(fqdn string) {
	o.Fqdn = fqdn
}

// WithNumber adds the number to the get Api v3 switches fqdn ports number params
func (o *GetAPIV3SwitchesFqdnPortsNumberParams) WithNumber(number int32) *GetAPIV3SwitchesFqdnPortsNumberParams {
	o.SetNumber(number)
	return o
}

// SetNumber adds the number to the get Api v3 switches fqdn ports number params
func (o *GetAPIV3SwitchesFqdnPortsNumberParams) SetNumber(number int32) {
	o.Number = number
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV3SwitchesFqdnPortsNumberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param fqdn
	if err := r.SetPathParam("fqdn", o.Fqdn); err != nil {
		return err
	}

	// path param number
	if err := r.SetPathParam("number", swag.FormatInt32(o.Number)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
