// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAPIV3InventoriesInventoryNumberAttachmentsParams creates a new GetAPIV3InventoriesInventoryNumberAttachmentsParams object
// with the default values initialized.
func NewGetAPIV3InventoriesInventoryNumberAttachmentsParams() *GetAPIV3InventoriesInventoryNumberAttachmentsParams {
	var ()
	return &GetAPIV3InventoriesInventoryNumberAttachmentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV3InventoriesInventoryNumberAttachmentsParamsWithTimeout creates a new GetAPIV3InventoriesInventoryNumberAttachmentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV3InventoriesInventoryNumberAttachmentsParamsWithTimeout(timeout time.Duration) *GetAPIV3InventoriesInventoryNumberAttachmentsParams {
	var ()
	return &GetAPIV3InventoriesInventoryNumberAttachmentsParams{

		timeout: timeout,
	}
}

// NewGetAPIV3InventoriesInventoryNumberAttachmentsParamsWithContext creates a new GetAPIV3InventoriesInventoryNumberAttachmentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV3InventoriesInventoryNumberAttachmentsParamsWithContext(ctx context.Context) *GetAPIV3InventoriesInventoryNumberAttachmentsParams {
	var ()
	return &GetAPIV3InventoriesInventoryNumberAttachmentsParams{

		Context: ctx,
	}
}

// NewGetAPIV3InventoriesInventoryNumberAttachmentsParamsWithHTTPClient creates a new GetAPIV3InventoriesInventoryNumberAttachmentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV3InventoriesInventoryNumberAttachmentsParamsWithHTTPClient(client *http.Client) *GetAPIV3InventoriesInventoryNumberAttachmentsParams {
	var ()
	return &GetAPIV3InventoriesInventoryNumberAttachmentsParams{
		HTTPClient: client,
	}
}

/*GetAPIV3InventoriesInventoryNumberAttachmentsParams contains all the parameters to send to the API endpoint
for the get Api v3 inventories inventory number attachments operation typically these are written to a http.Request
*/
type GetAPIV3InventoriesInventoryNumberAttachmentsParams struct {

	/*InventoryNumber*/
	InventoryNumber string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get Api v3 inventories inventory number attachments params
func (o *GetAPIV3InventoriesInventoryNumberAttachmentsParams) WithTimeout(timeout time.Duration) *GetAPIV3InventoriesInventoryNumberAttachmentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Api v3 inventories inventory number attachments params
func (o *GetAPIV3InventoriesInventoryNumberAttachmentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Api v3 inventories inventory number attachments params
func (o *GetAPIV3InventoriesInventoryNumberAttachmentsParams) WithContext(ctx context.Context) *GetAPIV3InventoriesInventoryNumberAttachmentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Api v3 inventories inventory number attachments params
func (o *GetAPIV3InventoriesInventoryNumberAttachmentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get Api v3 inventories inventory number attachments params
func (o *GetAPIV3InventoriesInventoryNumberAttachmentsParams) WithHTTPClient(client *http.Client) *GetAPIV3InventoriesInventoryNumberAttachmentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get Api v3 inventories inventory number attachments params
func (o *GetAPIV3InventoriesInventoryNumberAttachmentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInventoryNumber adds the inventoryNumber to the get Api v3 inventories inventory number attachments params
func (o *GetAPIV3InventoriesInventoryNumberAttachmentsParams) WithInventoryNumber(inventoryNumber string) *GetAPIV3InventoriesInventoryNumberAttachmentsParams {
	o.SetInventoryNumber(inventoryNumber)
	return o
}

// SetInventoryNumber adds the inventoryNumber to the get Api v3 inventories inventory number attachments params
func (o *GetAPIV3InventoriesInventoryNumberAttachmentsParams) SetInventoryNumber(inventoryNumber string) {
	o.InventoryNumber = inventoryNumber
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV3InventoriesInventoryNumberAttachmentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param inventory_number
	if err := r.SetPathParam("inventory_number", o.InventoryNumber); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
