// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// NewPostAPIV3NicsParams creates a new PostAPIV3NicsParams object
// with the default values initialized.
func NewPostAPIV3NicsParams() *PostAPIV3NicsParams {
	var ()
	return &PostAPIV3NicsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV3NicsParamsWithTimeout creates a new PostAPIV3NicsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIV3NicsParamsWithTimeout(timeout time.Duration) *PostAPIV3NicsParams {
	var ()
	return &PostAPIV3NicsParams{

		timeout: timeout,
	}
}

// NewPostAPIV3NicsParamsWithContext creates a new PostAPIV3NicsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIV3NicsParamsWithContext(ctx context.Context) *PostAPIV3NicsParams {
	var ()
	return &PostAPIV3NicsParams{

		Context: ctx,
	}
}

// NewPostAPIV3NicsParamsWithHTTPClient creates a new PostAPIV3NicsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIV3NicsParamsWithHTTPClient(client *http.Client) *PostAPIV3NicsParams {
	var ()
	return &PostAPIV3NicsParams{
		HTTPClient: client,
	}
}

/*PostAPIV3NicsParams contains all the parameters to send to the API endpoint
for the post Api v3 nics operation typically these are written to a http.Request
*/
type PostAPIV3NicsParams struct {

	/*Nic*/
	Nic *models.Nic

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post Api v3 nics params
func (o *PostAPIV3NicsParams) WithTimeout(timeout time.Duration) *PostAPIV3NicsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post Api v3 nics params
func (o *PostAPIV3NicsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post Api v3 nics params
func (o *PostAPIV3NicsParams) WithContext(ctx context.Context) *PostAPIV3NicsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post Api v3 nics params
func (o *PostAPIV3NicsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post Api v3 nics params
func (o *PostAPIV3NicsParams) WithHTTPClient(client *http.Client) *PostAPIV3NicsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post Api v3 nics params
func (o *PostAPIV3NicsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNic adds the nic to the post Api v3 nics params
func (o *PostAPIV3NicsParams) WithNic(nic *models.Nic) *PostAPIV3NicsParams {
	o.SetNic(nic)
	return o
}

// SetNic adds the nic to the post Api v3 nics params
func (o *PostAPIV3NicsParams) SetNic(nic *models.Nic) {
	o.Nic = nic
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV3NicsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Nic == nil {
		o.Nic = new(models.Nic)
	}

	if err := r.SetBodyParam(o.Nic); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
