// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// PostAPIV3MachinesRfqdnAttachmentsReader is a Reader for the PostAPIV3MachinesRfqdnAttachments structure.
type PostAPIV3MachinesRfqdnAttachmentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV3MachinesRfqdnAttachmentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostAPIV3MachinesRfqdnAttachmentsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAPIV3MachinesRfqdnAttachmentsCreated creates a PostAPIV3MachinesRfqdnAttachmentsCreated with default headers values
func NewPostAPIV3MachinesRfqdnAttachmentsCreated() *PostAPIV3MachinesRfqdnAttachmentsCreated {
	return &PostAPIV3MachinesRfqdnAttachmentsCreated{}
}

/*PostAPIV3MachinesRfqdnAttachmentsCreated handles this case with default header values.

Create an attachment
*/
type PostAPIV3MachinesRfqdnAttachmentsCreated struct {
	Payload *models.Attachment
}

func (o *PostAPIV3MachinesRfqdnAttachmentsCreated) Error() string {
	return fmt.Sprintf("[POST /api/v3/machines/{rfqdn}/attachments][%d] postApiV3MachinesRfqdnAttachmentsCreated  %+v", 201, o.Payload)
}

func (o *PostAPIV3MachinesRfqdnAttachmentsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Attachment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
