// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// NewPostAPIV3CloudProvidersParams creates a new PostAPIV3CloudProvidersParams object
// with the default values initialized.
func NewPostAPIV3CloudProvidersParams() *PostAPIV3CloudProvidersParams {
	var ()
	return &PostAPIV3CloudProvidersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV3CloudProvidersParamsWithTimeout creates a new PostAPIV3CloudProvidersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIV3CloudProvidersParamsWithTimeout(timeout time.Duration) *PostAPIV3CloudProvidersParams {
	var ()
	return &PostAPIV3CloudProvidersParams{

		timeout: timeout,
	}
}

// NewPostAPIV3CloudProvidersParamsWithContext creates a new PostAPIV3CloudProvidersParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIV3CloudProvidersParamsWithContext(ctx context.Context) *PostAPIV3CloudProvidersParams {
	var ()
	return &PostAPIV3CloudProvidersParams{

		Context: ctx,
	}
}

// NewPostAPIV3CloudProvidersParamsWithHTTPClient creates a new PostAPIV3CloudProvidersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIV3CloudProvidersParamsWithHTTPClient(client *http.Client) *PostAPIV3CloudProvidersParams {
	var ()
	return &PostAPIV3CloudProvidersParams{
		HTTPClient: client,
	}
}

/*PostAPIV3CloudProvidersParams contains all the parameters to send to the API endpoint
for the post Api v3 cloud providers operation typically these are written to a http.Request
*/
type PostAPIV3CloudProvidersParams struct {

	/*CloudProvider*/
	CloudProvider *models.CloudProvider

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) WithTimeout(timeout time.Duration) *PostAPIV3CloudProvidersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) WithContext(ctx context.Context) *PostAPIV3CloudProvidersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) WithHTTPClient(client *http.Client) *PostAPIV3CloudProvidersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCloudProvider adds the cloudProvider to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) WithCloudProvider(cloudProvider *models.CloudProvider) *PostAPIV3CloudProvidersParams {
	o.SetCloudProvider(cloudProvider)
	return o
}

// SetCloudProvider adds the cloudProvider to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) SetCloudProvider(cloudProvider *models.CloudProvider) {
	o.CloudProvider = cloudProvider
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV3CloudProvidersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CloudProvider == nil {
		o.CloudProvider = new(models.CloudProvider)
	}

	if err := r.SetBodyParam(o.CloudProvider); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
