// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// NewPutAPIV3LocationsIDIDParams creates a new PutAPIV3LocationsIDIDParams object
// with the default values initialized.
func NewPutAPIV3LocationsIDIDParams() *PutAPIV3LocationsIDIDParams {
	var ()
	return &PutAPIV3LocationsIDIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV3LocationsIDIDParamsWithTimeout creates a new PutAPIV3LocationsIDIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAPIV3LocationsIDIDParamsWithTimeout(timeout time.Duration) *PutAPIV3LocationsIDIDParams {
	var ()
	return &PutAPIV3LocationsIDIDParams{

		timeout: timeout,
	}
}

// NewPutAPIV3LocationsIDIDParamsWithContext creates a new PutAPIV3LocationsIDIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAPIV3LocationsIDIDParamsWithContext(ctx context.Context) *PutAPIV3LocationsIDIDParams {
	var ()
	return &PutAPIV3LocationsIDIDParams{

		Context: ctx,
	}
}

// NewPutAPIV3LocationsIDIDParamsWithHTTPClient creates a new PutAPIV3LocationsIDIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAPIV3LocationsIDIDParamsWithHTTPClient(client *http.Client) *PutAPIV3LocationsIDIDParams {
	var ()
	return &PutAPIV3LocationsIDIDParams{
		HTTPClient: client,
	}
}

/*PutAPIV3LocationsIDIDParams contains all the parameters to send to the API endpoint
for the put Api v3 locations Id Id operation typically these are written to a http.Request
*/
type PutAPIV3LocationsIDIDParams struct {

	/*Location*/
	Location *models.Location
	/*ID
	  Id

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put Api v3 locations Id Id params
func (o *PutAPIV3LocationsIDIDParams) WithTimeout(timeout time.Duration) *PutAPIV3LocationsIDIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put Api v3 locations Id Id params
func (o *PutAPIV3LocationsIDIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put Api v3 locations Id Id params
func (o *PutAPIV3LocationsIDIDParams) WithContext(ctx context.Context) *PutAPIV3LocationsIDIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put Api v3 locations Id Id params
func (o *PutAPIV3LocationsIDIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put Api v3 locations Id Id params
func (o *PutAPIV3LocationsIDIDParams) WithHTTPClient(client *http.Client) *PutAPIV3LocationsIDIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put Api v3 locations Id Id params
func (o *PutAPIV3LocationsIDIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLocation adds the location to the put Api v3 locations Id Id params
func (o *PutAPIV3LocationsIDIDParams) WithLocation(location *models.Location) *PutAPIV3LocationsIDIDParams {
	o.SetLocation(location)
	return o
}

// SetLocation adds the location to the put Api v3 locations Id Id params
func (o *PutAPIV3LocationsIDIDParams) SetLocation(location *models.Location) {
	o.Location = location
}

// WithID adds the id to the put Api v3 locations Id Id params
func (o *PutAPIV3LocationsIDIDParams) WithID(id int32) *PutAPIV3LocationsIDIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put Api v3 locations Id Id params
func (o *PutAPIV3LocationsIDIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV3LocationsIDIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Location == nil {
		o.Location = new(models.Location)
	}

	if err := r.SetBodyParam(o.Location); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
