// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// NewPutAPIV3InventoriesInventoryNumberParams creates a new PutAPIV3InventoriesInventoryNumberParams object
// with the default values initialized.
func NewPutAPIV3InventoriesInventoryNumberParams() *PutAPIV3InventoriesInventoryNumberParams {
	var ()
	return &PutAPIV3InventoriesInventoryNumberParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV3InventoriesInventoryNumberParamsWithTimeout creates a new PutAPIV3InventoriesInventoryNumberParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAPIV3InventoriesInventoryNumberParamsWithTimeout(timeout time.Duration) *PutAPIV3InventoriesInventoryNumberParams {
	var ()
	return &PutAPIV3InventoriesInventoryNumberParams{

		timeout: timeout,
	}
}

// NewPutAPIV3InventoriesInventoryNumberParamsWithContext creates a new PutAPIV3InventoriesInventoryNumberParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAPIV3InventoriesInventoryNumberParamsWithContext(ctx context.Context) *PutAPIV3InventoriesInventoryNumberParams {
	var ()
	return &PutAPIV3InventoriesInventoryNumberParams{

		Context: ctx,
	}
}

// NewPutAPIV3InventoriesInventoryNumberParamsWithHTTPClient creates a new PutAPIV3InventoriesInventoryNumberParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAPIV3InventoriesInventoryNumberParamsWithHTTPClient(client *http.Client) *PutAPIV3InventoriesInventoryNumberParams {
	var ()
	return &PutAPIV3InventoriesInventoryNumberParams{
		HTTPClient: client,
	}
}

/*PutAPIV3InventoriesInventoryNumberParams contains all the parameters to send to the API endpoint
for the put Api v3 inventories inventory number operation typically these are written to a http.Request
*/
type PutAPIV3InventoriesInventoryNumberParams struct {

	/*Inventory*/
	Inventory *models.Inventory
	/*InventoryNumber
	  Inventory Number

	*/
	InventoryNumber string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put Api v3 inventories inventory number params
func (o *PutAPIV3InventoriesInventoryNumberParams) WithTimeout(timeout time.Duration) *PutAPIV3InventoriesInventoryNumberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put Api v3 inventories inventory number params
func (o *PutAPIV3InventoriesInventoryNumberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put Api v3 inventories inventory number params
func (o *PutAPIV3InventoriesInventoryNumberParams) WithContext(ctx context.Context) *PutAPIV3InventoriesInventoryNumberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put Api v3 inventories inventory number params
func (o *PutAPIV3InventoriesInventoryNumberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put Api v3 inventories inventory number params
func (o *PutAPIV3InventoriesInventoryNumberParams) WithHTTPClient(client *http.Client) *PutAPIV3InventoriesInventoryNumberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put Api v3 inventories inventory number params
func (o *PutAPIV3InventoriesInventoryNumberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInventory adds the inventory to the put Api v3 inventories inventory number params
func (o *PutAPIV3InventoriesInventoryNumberParams) WithInventory(inventory *models.Inventory) *PutAPIV3InventoriesInventoryNumberParams {
	o.SetInventory(inventory)
	return o
}

// SetInventory adds the inventory to the put Api v3 inventories inventory number params
func (o *PutAPIV3InventoriesInventoryNumberParams) SetInventory(inventory *models.Inventory) {
	o.Inventory = inventory
}

// WithInventoryNumber adds the inventoryNumber to the put Api v3 inventories inventory number params
func (o *PutAPIV3InventoriesInventoryNumberParams) WithInventoryNumber(inventoryNumber string) *PutAPIV3InventoriesInventoryNumberParams {
	o.SetInventoryNumber(inventoryNumber)
	return o
}

// SetInventoryNumber adds the inventoryNumber to the put Api v3 inventories inventory number params
func (o *PutAPIV3InventoriesInventoryNumberParams) SetInventoryNumber(inventoryNumber string) {
	o.InventoryNumber = inventoryNumber
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV3InventoriesInventoryNumberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Inventory == nil {
		o.Inventory = new(models.Inventory)
	}

	if err := r.SetBodyParam(o.Inventory); err != nil {
		return err
	}

	// path param inventory_number
	if err := r.SetPathParam("inventory_number", o.InventoryNumber); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
