// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// NewPutAPIV3CloudProvidersRnameParams creates a new PutAPIV3CloudProvidersRnameParams object
// with the default values initialized.
func NewPutAPIV3CloudProvidersRnameParams() *PutAPIV3CloudProvidersRnameParams {
	var ()
	return &PutAPIV3CloudProvidersRnameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV3CloudProvidersRnameParamsWithTimeout creates a new PutAPIV3CloudProvidersRnameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAPIV3CloudProvidersRnameParamsWithTimeout(timeout time.Duration) *PutAPIV3CloudProvidersRnameParams {
	var ()
	return &PutAPIV3CloudProvidersRnameParams{

		timeout: timeout,
	}
}

// NewPutAPIV3CloudProvidersRnameParamsWithContext creates a new PutAPIV3CloudProvidersRnameParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAPIV3CloudProvidersRnameParamsWithContext(ctx context.Context) *PutAPIV3CloudProvidersRnameParams {
	var ()
	return &PutAPIV3CloudProvidersRnameParams{

		Context: ctx,
	}
}

// NewPutAPIV3CloudProvidersRnameParamsWithHTTPClient creates a new PutAPIV3CloudProvidersRnameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAPIV3CloudProvidersRnameParamsWithHTTPClient(client *http.Client) *PutAPIV3CloudProvidersRnameParams {
	var ()
	return &PutAPIV3CloudProvidersRnameParams{
		HTTPClient: client,
	}
}

/*PutAPIV3CloudProvidersRnameParams contains all the parameters to send to the API endpoint
for the put Api v3 cloud providers rname operation typically these are written to a http.Request
*/
type PutAPIV3CloudProvidersRnameParams struct {

	/*CloudProvider*/
	CloudProvider *models.CloudProvider
	/*Rname*/
	Rname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put Api v3 cloud providers rname params
func (o *PutAPIV3CloudProvidersRnameParams) WithTimeout(timeout time.Duration) *PutAPIV3CloudProvidersRnameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put Api v3 cloud providers rname params
func (o *PutAPIV3CloudProvidersRnameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put Api v3 cloud providers rname params
func (o *PutAPIV3CloudProvidersRnameParams) WithContext(ctx context.Context) *PutAPIV3CloudProvidersRnameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put Api v3 cloud providers rname params
func (o *PutAPIV3CloudProvidersRnameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put Api v3 cloud providers rname params
func (o *PutAPIV3CloudProvidersRnameParams) WithHTTPClient(client *http.Client) *PutAPIV3CloudProvidersRnameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put Api v3 cloud providers rname params
func (o *PutAPIV3CloudProvidersRnameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCloudProvider adds the cloudProvider to the put Api v3 cloud providers rname params
func (o *PutAPIV3CloudProvidersRnameParams) WithCloudProvider(cloudProvider *models.CloudProvider) *PutAPIV3CloudProvidersRnameParams {
	o.SetCloudProvider(cloudProvider)
	return o
}

// SetCloudProvider adds the cloudProvider to the put Api v3 cloud providers rname params
func (o *PutAPIV3CloudProvidersRnameParams) SetCloudProvider(cloudProvider *models.CloudProvider) {
	o.CloudProvider = cloudProvider
}

// WithRname adds the rname to the put Api v3 cloud providers rname params
func (o *PutAPIV3CloudProvidersRnameParams) WithRname(rname string) *PutAPIV3CloudProvidersRnameParams {
	o.SetRname(rname)
	return o
}

// SetRname adds the rname to the put Api v3 cloud providers rname params
func (o *PutAPIV3CloudProvidersRnameParams) SetRname(rname string) {
	o.Rname = rname
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV3CloudProvidersRnameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CloudProvider == nil {
		o.CloudProvider = new(models.CloudProvider)
	}

	if err := r.SetBodyParam(o.CloudProvider); err != nil {
		return err
	}

	// path param rname
	if err := r.SetPathParam("rname", o.Rname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
