// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// NewPutAPIV3MachinesRfqdnAliasesAliasParams creates a new PutAPIV3MachinesRfqdnAliasesAliasParams object
// with the default values initialized.
func NewPutAPIV3MachinesRfqdnAliasesAliasParams() *PutAPIV3MachinesRfqdnAliasesAliasParams {
	var ()
	return &PutAPIV3MachinesRfqdnAliasesAliasParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV3MachinesRfqdnAliasesAliasParamsWithTimeout creates a new PutAPIV3MachinesRfqdnAliasesAliasParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAPIV3MachinesRfqdnAliasesAliasParamsWithTimeout(timeout time.Duration) *PutAPIV3MachinesRfqdnAliasesAliasParams {
	var ()
	return &PutAPIV3MachinesRfqdnAliasesAliasParams{

		timeout: timeout,
	}
}

// NewPutAPIV3MachinesRfqdnAliasesAliasParamsWithContext creates a new PutAPIV3MachinesRfqdnAliasesAliasParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAPIV3MachinesRfqdnAliasesAliasParamsWithContext(ctx context.Context) *PutAPIV3MachinesRfqdnAliasesAliasParams {
	var ()
	return &PutAPIV3MachinesRfqdnAliasesAliasParams{

		Context: ctx,
	}
}

// NewPutAPIV3MachinesRfqdnAliasesAliasParamsWithHTTPClient creates a new PutAPIV3MachinesRfqdnAliasesAliasParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAPIV3MachinesRfqdnAliasesAliasParamsWithHTTPClient(client *http.Client) *PutAPIV3MachinesRfqdnAliasesAliasParams {
	var ()
	return &PutAPIV3MachinesRfqdnAliasesAliasParams{
		HTTPClient: client,
	}
}

/*PutAPIV3MachinesRfqdnAliasesAliasParams contains all the parameters to send to the API endpoint
for the put Api v3 machines rfqdn aliases alias operation typically these are written to a http.Request
*/
type PutAPIV3MachinesRfqdnAliasesAliasParams struct {

	/*MachineAlias*/
	MachineAlias *models.MachineAlias
	/*Alias*/
	Alias string
	/*Rfqdn*/
	Rfqdn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put Api v3 machines rfqdn aliases alias params
func (o *PutAPIV3MachinesRfqdnAliasesAliasParams) WithTimeout(timeout time.Duration) *PutAPIV3MachinesRfqdnAliasesAliasParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put Api v3 machines rfqdn aliases alias params
func (o *PutAPIV3MachinesRfqdnAliasesAliasParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put Api v3 machines rfqdn aliases alias params
func (o *PutAPIV3MachinesRfqdnAliasesAliasParams) WithContext(ctx context.Context) *PutAPIV3MachinesRfqdnAliasesAliasParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put Api v3 machines rfqdn aliases alias params
func (o *PutAPIV3MachinesRfqdnAliasesAliasParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put Api v3 machines rfqdn aliases alias params
func (o *PutAPIV3MachinesRfqdnAliasesAliasParams) WithHTTPClient(client *http.Client) *PutAPIV3MachinesRfqdnAliasesAliasParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put Api v3 machines rfqdn aliases alias params
func (o *PutAPIV3MachinesRfqdnAliasesAliasParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMachineAlias adds the machineAlias to the put Api v3 machines rfqdn aliases alias params
func (o *PutAPIV3MachinesRfqdnAliasesAliasParams) WithMachineAlias(machineAlias *models.MachineAlias) *PutAPIV3MachinesRfqdnAliasesAliasParams {
	o.SetMachineAlias(machineAlias)
	return o
}

// SetMachineAlias adds the machineAlias to the put Api v3 machines rfqdn aliases alias params
func (o *PutAPIV3MachinesRfqdnAliasesAliasParams) SetMachineAlias(machineAlias *models.MachineAlias) {
	o.MachineAlias = machineAlias
}

// WithAlias adds the alias to the put Api v3 machines rfqdn aliases alias params
func (o *PutAPIV3MachinesRfqdnAliasesAliasParams) WithAlias(alias string) *PutAPIV3MachinesRfqdnAliasesAliasParams {
	o.SetAlias(alias)
	return o
}

// SetAlias adds the alias to the put Api v3 machines rfqdn aliases alias params
func (o *PutAPIV3MachinesRfqdnAliasesAliasParams) SetAlias(alias string) {
	o.Alias = alias
}

// WithRfqdn adds the rfqdn to the put Api v3 machines rfqdn aliases alias params
func (o *PutAPIV3MachinesRfqdnAliasesAliasParams) WithRfqdn(rfqdn string) *PutAPIV3MachinesRfqdnAliasesAliasParams {
	o.SetRfqdn(rfqdn)
	return o
}

// SetRfqdn adds the rfqdn to the put Api v3 machines rfqdn aliases alias params
func (o *PutAPIV3MachinesRfqdnAliasesAliasParams) SetRfqdn(rfqdn string) {
	o.Rfqdn = rfqdn
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV3MachinesRfqdnAliasesAliasParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.MachineAlias == nil {
		o.MachineAlias = new(models.MachineAlias)
	}

	if err := r.SetBodyParam(o.MachineAlias); err != nil {
		return err
	}

	// path param alias
	if err := r.SetPathParam("alias", o.Alias); err != nil {
		return err
	}

	// path param rfqdn
	if err := r.SetPathParam("rfqdn", o.Rfqdn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
