// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// PutAPIV3CloudProvidersRnameReader is a Reader for the PutAPIV3CloudProvidersRname structure.
type PutAPIV3CloudProvidersRnameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIV3CloudProvidersRnameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutAPIV3CloudProvidersRnameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutAPIV3CloudProvidersRnameOK creates a PutAPIV3CloudProvidersRnameOK with default headers values
func NewPutAPIV3CloudProvidersRnameOK() *PutAPIV3CloudProvidersRnameOK {
	return &PutAPIV3CloudProvidersRnameOK{}
}

/*PutAPIV3CloudProvidersRnameOK handles this case with default header values.

Update a single cloud provider
*/
type PutAPIV3CloudProvidersRnameOK struct {
	Payload *models.CloudProvider
}

func (o *PutAPIV3CloudProvidersRnameOK) Error() string {
	return fmt.Sprintf("[PUT /api/v3/cloud_providers/{rname}][%d] putApiV3CloudProvidersRnameOK  %+v", 200, o.Payload)
}

func (o *PutAPIV3CloudProvidersRnameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudProvider)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
