// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// PutAPIV3LocationsIDIDReader is a Reader for the PutAPIV3LocationsIDID structure.
type PutAPIV3LocationsIDIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIV3LocationsIDIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutAPIV3LocationsIDIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutAPIV3LocationsIDIDOK creates a PutAPIV3LocationsIDIDOK with default headers values
func NewPutAPIV3LocationsIDIDOK() *PutAPIV3LocationsIDIDOK {
	return &PutAPIV3LocationsIDIDOK{}
}

/*PutAPIV3LocationsIDIDOK handles this case with default header values.

Update a location
*/
type PutAPIV3LocationsIDIDOK struct {
	Payload *models.Location
}

func (o *PutAPIV3LocationsIDIDOK) Error() string {
	return fmt.Sprintf("[PUT /api/v3/locations/id/{id}][%d] putApiV3LocationsIdIdOK  %+v", 200, o.Payload)
}

func (o *PutAPIV3LocationsIDIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Location)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
