// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams creates a new DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams object
// with the default values initialized.
func NewDeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams() *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams {
	var ()
	return &DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIV3MachinesRfqdnAttachmentsFingerprintParamsWithTimeout creates a new DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAPIV3MachinesRfqdnAttachmentsFingerprintParamsWithTimeout(timeout time.Duration) *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams {
	var ()
	return &DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams{

		timeout: timeout,
	}
}

// NewDeleteAPIV3MachinesRfqdnAttachmentsFingerprintParamsWithContext creates a new DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteAPIV3MachinesRfqdnAttachmentsFingerprintParamsWithContext(ctx context.Context) *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams {
	var ()
	return &DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams{

		Context: ctx,
	}
}

// NewDeleteAPIV3MachinesRfqdnAttachmentsFingerprintParamsWithHTTPClient creates a new DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteAPIV3MachinesRfqdnAttachmentsFingerprintParamsWithHTTPClient(client *http.Client) *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams {
	var ()
	return &DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams{
		HTTPClient: client,
	}
}

/*DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams contains all the parameters to send to the API endpoint
for the delete Api v3 machines rfqdn attachments fingerprint operation typically these are written to a http.Request
*/
type DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams struct {

	/*Fingerprint*/
	Fingerprint string
	/*Rfqdn*/
	Rfqdn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete Api v3 machines rfqdn attachments fingerprint params
func (o *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams) WithTimeout(timeout time.Duration) *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete Api v3 machines rfqdn attachments fingerprint params
func (o *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete Api v3 machines rfqdn attachments fingerprint params
func (o *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams) WithContext(ctx context.Context) *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete Api v3 machines rfqdn attachments fingerprint params
func (o *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete Api v3 machines rfqdn attachments fingerprint params
func (o *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams) WithHTTPClient(client *http.Client) *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete Api v3 machines rfqdn attachments fingerprint params
func (o *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFingerprint adds the fingerprint to the delete Api v3 machines rfqdn attachments fingerprint params
func (o *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams) WithFingerprint(fingerprint string) *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams {
	o.SetFingerprint(fingerprint)
	return o
}

// SetFingerprint adds the fingerprint to the delete Api v3 machines rfqdn attachments fingerprint params
func (o *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams) SetFingerprint(fingerprint string) {
	o.Fingerprint = fingerprint
}

// WithRfqdn adds the rfqdn to the delete Api v3 machines rfqdn attachments fingerprint params
func (o *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams) WithRfqdn(rfqdn string) *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams {
	o.SetRfqdn(rfqdn)
	return o
}

// SetRfqdn adds the rfqdn to the delete Api v3 machines rfqdn attachments fingerprint params
func (o *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams) SetRfqdn(rfqdn string) {
	o.Rfqdn = rfqdn
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIV3MachinesRfqdnAttachmentsFingerprintParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param fingerprint
	if err := r.SetPathParam("fingerprint", o.Fingerprint); err != nil {
		return err
	}

	// path param rfqdn
	if err := r.SetPathParam("rfqdn", o.Rfqdn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
