// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteAPIV3MachinesRfqdnAliasesAliasReader is a Reader for the DeleteAPIV3MachinesRfqdnAliasesAlias structure.
type DeleteAPIV3MachinesRfqdnAliasesAliasReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIV3MachinesRfqdnAliasesAliasReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteAPIV3MachinesRfqdnAliasesAliasNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAPIV3MachinesRfqdnAliasesAliasNoContent creates a DeleteAPIV3MachinesRfqdnAliasesAliasNoContent with default headers values
func NewDeleteAPIV3MachinesRfqdnAliasesAliasNoContent() *DeleteAPIV3MachinesRfqdnAliasesAliasNoContent {
	return &DeleteAPIV3MachinesRfqdnAliasesAliasNoContent{}
}

/*DeleteAPIV3MachinesRfqdnAliasesAliasNoContent handles this case with default header values.

Delete an alias
*/
type DeleteAPIV3MachinesRfqdnAliasesAliasNoContent struct {
}

func (o *DeleteAPIV3MachinesRfqdnAliasesAliasNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/machines/{rfqdn}/aliases/{alias}][%d] deleteApiV3MachinesRfqdnAliasesAliasNoContent ", 204)
}

func (o *DeleteAPIV3MachinesRfqdnAliasesAliasNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
