// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteAPIV3MachinesRfqdnNicsNameReader is a Reader for the DeleteAPIV3MachinesRfqdnNicsName structure.
type DeleteAPIV3MachinesRfqdnNicsNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIV3MachinesRfqdnNicsNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteAPIV3MachinesRfqdnNicsNameNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAPIV3MachinesRfqdnNicsNameNoContent creates a DeleteAPIV3MachinesRfqdnNicsNameNoContent with default headers values
func NewDeleteAPIV3MachinesRfqdnNicsNameNoContent() *DeleteAPIV3MachinesRfqdnNicsNameNoContent {
	return &DeleteAPIV3MachinesRfqdnNicsNameNoContent{}
}

/*DeleteAPIV3MachinesRfqdnNicsNameNoContent handles this case with default header values.

Delete a nic
*/
type DeleteAPIV3MachinesRfqdnNicsNameNoContent struct {
}

func (o *DeleteAPIV3MachinesRfqdnNicsNameNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v3/machines/{rfqdn}/nics/{name}][%d] deleteApiV3MachinesRfqdnNicsNameNoContent ", 204)
}

func (o *DeleteAPIV3MachinesRfqdnNicsNameNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
