// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// GetAPIV3MachinesRfqdnNicsNameReader is a Reader for the GetAPIV3MachinesRfqdnNicsName structure.
type GetAPIV3MachinesRfqdnNicsNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3MachinesRfqdnNicsNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV3MachinesRfqdnNicsNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV3MachinesRfqdnNicsNameOK creates a GetAPIV3MachinesRfqdnNicsNameOK with default headers values
func NewGetAPIV3MachinesRfqdnNicsNameOK() *GetAPIV3MachinesRfqdnNicsNameOK {
	return &GetAPIV3MachinesRfqdnNicsNameOK{}
}

/*GetAPIV3MachinesRfqdnNicsNameOK handles this case with default header values.

Get a nic
*/
type GetAPIV3MachinesRfqdnNicsNameOK struct {
	Payload *models.Nic
}

func (o *GetAPIV3MachinesRfqdnNicsNameOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/machines/{rfqdn}/nics/{name}][%d] getApiV3MachinesRfqdnNicsNameOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3MachinesRfqdnNicsNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Nic)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
