// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// GetAPIV3MachinesRfqdnReader is a Reader for the GetAPIV3MachinesRfqdn structure.
type GetAPIV3MachinesRfqdnReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3MachinesRfqdnReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV3MachinesRfqdnOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV3MachinesRfqdnOK creates a GetAPIV3MachinesRfqdnOK with default headers values
func NewGetAPIV3MachinesRfqdnOK() *GetAPIV3MachinesRfqdnOK {
	return &GetAPIV3MachinesRfqdnOK{}
}

/*GetAPIV3MachinesRfqdnOK handles this case with default header values.

Get a machine by fqdn
*/
type GetAPIV3MachinesRfqdnOK struct {
	Payload *models.Machine
}

func (o *GetAPIV3MachinesRfqdnOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/machines/{rfqdn}][%d] getApiV3MachinesRfqdnOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3MachinesRfqdnOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Machine)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
