// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// PostAPIV3MachinesReader is a Reader for the PostAPIV3Machines structure.
type PostAPIV3MachinesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV3MachinesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostAPIV3MachinesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAPIV3MachinesCreated creates a PostAPIV3MachinesCreated with default headers values
func NewPostAPIV3MachinesCreated() *PostAPIV3MachinesCreated {
	return &PostAPIV3MachinesCreated{}
}

/*PostAPIV3MachinesCreated handles this case with default header values.

Create a new machine
*/
type PostAPIV3MachinesCreated struct {
	Payload *models.Machine
}

func (o *PostAPIV3MachinesCreated) Error() string {
	return fmt.Sprintf("[POST /api/v3/machines][%d] postApiV3MachinesCreated  %+v", 201, o.Payload)
}

func (o *PostAPIV3MachinesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Machine)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
