// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// PostAPIV3MachinesRfqdnNicsReader is a Reader for the PostAPIV3MachinesRfqdnNics structure.
type PostAPIV3MachinesRfqdnNicsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV3MachinesRfqdnNicsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostAPIV3MachinesRfqdnNicsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAPIV3MachinesRfqdnNicsCreated creates a PostAPIV3MachinesRfqdnNicsCreated with default headers values
func NewPostAPIV3MachinesRfqdnNicsCreated() *PostAPIV3MachinesRfqdnNicsCreated {
	return &PostAPIV3MachinesRfqdnNicsCreated{}
}

/*PostAPIV3MachinesRfqdnNicsCreated handles this case with default header values.

Create a nic
*/
type PostAPIV3MachinesRfqdnNicsCreated struct {
	Payload *models.Nic
}

func (o *PostAPIV3MachinesRfqdnNicsCreated) Error() string {
	return fmt.Sprintf("[POST /api/v3/machines/{rfqdn}/nics][%d] postApiV3MachinesRfqdnNicsCreated  %+v", 201, o.Payload)
}

func (o *PostAPIV3MachinesRfqdnNicsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Nic)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
