// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// PutAPIV3MachinesRfqdnAliasesAliasReader is a Reader for the PutAPIV3MachinesRfqdnAliasesAlias structure.
type PutAPIV3MachinesRfqdnAliasesAliasReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIV3MachinesRfqdnAliasesAliasReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutAPIV3MachinesRfqdnAliasesAliasOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutAPIV3MachinesRfqdnAliasesAliasOK creates a PutAPIV3MachinesRfqdnAliasesAliasOK with default headers values
func NewPutAPIV3MachinesRfqdnAliasesAliasOK() *PutAPIV3MachinesRfqdnAliasesAliasOK {
	return &PutAPIV3MachinesRfqdnAliasesAliasOK{}
}

/*PutAPIV3MachinesRfqdnAliasesAliasOK handles this case with default header values.

Update an alias
*/
type PutAPIV3MachinesRfqdnAliasesAliasOK struct {
	Payload *models.MachineAlias
}

func (o *PutAPIV3MachinesRfqdnAliasesAliasOK) Error() string {
	return fmt.Sprintf("[PUT /api/v3/machines/{rfqdn}/aliases/{alias}][%d] putApiV3MachinesRfqdnAliasesAliasOK  %+v", 200, o.Payload)
}

func (o *PutAPIV3MachinesRfqdnAliasesAliasOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MachineAlias)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
