// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutAPIV3MachinesRfqdnNicsNameParams creates a new PutAPIV3MachinesRfqdnNicsNameParams object
// with the default values initialized.
func NewPutAPIV3MachinesRfqdnNicsNameParams() *PutAPIV3MachinesRfqdnNicsNameParams {
	var ()
	return &PutAPIV3MachinesRfqdnNicsNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV3MachinesRfqdnNicsNameParamsWithTimeout creates a new PutAPIV3MachinesRfqdnNicsNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAPIV3MachinesRfqdnNicsNameParamsWithTimeout(timeout time.Duration) *PutAPIV3MachinesRfqdnNicsNameParams {
	var ()
	return &PutAPIV3MachinesRfqdnNicsNameParams{

		timeout: timeout,
	}
}

// NewPutAPIV3MachinesRfqdnNicsNameParamsWithContext creates a new PutAPIV3MachinesRfqdnNicsNameParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAPIV3MachinesRfqdnNicsNameParamsWithContext(ctx context.Context) *PutAPIV3MachinesRfqdnNicsNameParams {
	var ()
	return &PutAPIV3MachinesRfqdnNicsNameParams{

		Context: ctx,
	}
}

// NewPutAPIV3MachinesRfqdnNicsNameParamsWithHTTPClient creates a new PutAPIV3MachinesRfqdnNicsNameParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAPIV3MachinesRfqdnNicsNameParamsWithHTTPClient(client *http.Client) *PutAPIV3MachinesRfqdnNicsNameParams {
	var ()
	return &PutAPIV3MachinesRfqdnNicsNameParams{
		HTTPClient: client,
	}
}

/*PutAPIV3MachinesRfqdnNicsNameParams contains all the parameters to send to the API endpoint
for the put Api v3 machines rfqdn nics name operation typically these are written to a http.Request
*/
type PutAPIV3MachinesRfqdnNicsNameParams struct {

	/*Name*/
	Name string
	/*Rfqdn*/
	Rfqdn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put Api v3 machines rfqdn nics name params
func (o *PutAPIV3MachinesRfqdnNicsNameParams) WithTimeout(timeout time.Duration) *PutAPIV3MachinesRfqdnNicsNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put Api v3 machines rfqdn nics name params
func (o *PutAPIV3MachinesRfqdnNicsNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put Api v3 machines rfqdn nics name params
func (o *PutAPIV3MachinesRfqdnNicsNameParams) WithContext(ctx context.Context) *PutAPIV3MachinesRfqdnNicsNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put Api v3 machines rfqdn nics name params
func (o *PutAPIV3MachinesRfqdnNicsNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put Api v3 machines rfqdn nics name params
func (o *PutAPIV3MachinesRfqdnNicsNameParams) WithHTTPClient(client *http.Client) *PutAPIV3MachinesRfqdnNicsNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put Api v3 machines rfqdn nics name params
func (o *PutAPIV3MachinesRfqdnNicsNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the put Api v3 machines rfqdn nics name params
func (o *PutAPIV3MachinesRfqdnNicsNameParams) WithName(name string) *PutAPIV3MachinesRfqdnNicsNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the put Api v3 machines rfqdn nics name params
func (o *PutAPIV3MachinesRfqdnNicsNameParams) SetName(name string) {
	o.Name = name
}

// WithRfqdn adds the rfqdn to the put Api v3 machines rfqdn nics name params
func (o *PutAPIV3MachinesRfqdnNicsNameParams) WithRfqdn(rfqdn string) *PutAPIV3MachinesRfqdnNicsNameParams {
	o.SetRfqdn(rfqdn)
	return o
}

// SetRfqdn adds the rfqdn to the put Api v3 machines rfqdn nics name params
func (o *PutAPIV3MachinesRfqdnNicsNameParams) SetRfqdn(rfqdn string) {
	o.Rfqdn = rfqdn
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV3MachinesRfqdnNicsNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param rfqdn
	if err := r.SetPathParam("rfqdn", o.Rfqdn); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
