// Code generated by go-swagger; DO NOT EDIT.

package softwares

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new softwares API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for softwares API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetAPIV3Softwares searches machines with specific software configurations

Searches machines with specific software configurations
*/
func (a *Client) GetAPIV3Softwares(params *GetAPIV3SoftwaresParams) (*GetAPIV3SoftwaresOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetAPIV3SoftwaresParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getApiV3Softwares",
		Method:             "GET",
		PathPattern:        "/api/v3/softwares",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetAPIV3SoftwaresReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetAPIV3SoftwaresOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
