// Code generated by go-swagger; DO NOT EDIT.

package cloud_providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// GetAPIV3CloudProvidersNameReader is a Reader for the GetAPIV3CloudProvidersName structure.
type GetAPIV3CloudProvidersNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3CloudProvidersNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV3CloudProvidersNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV3CloudProvidersNameOK creates a GetAPIV3CloudProvidersNameOK with default headers values
func NewGetAPIV3CloudProvidersNameOK() *GetAPIV3CloudProvidersNameOK {
	return &GetAPIV3CloudProvidersNameOK{}
}

/*GetAPIV3CloudProvidersNameOK handles this case with default header values.

Delete cloud provider by name
*/
type GetAPIV3CloudProvidersNameOK struct {
	Payload *models.CloudProvider
}

func (o *GetAPIV3CloudProvidersNameOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/cloud_providers/{name}][%d] getApiV3CloudProvidersNameOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3CloudProvidersNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CloudProvider)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
