// Code generated by go-swagger; DO NOT EDIT.

package cloud_providers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostAPIV3CloudProvidersParams creates a new PostAPIV3CloudProvidersParams object
// with the default values initialized.
func NewPostAPIV3CloudProvidersParams() *PostAPIV3CloudProvidersParams {
	var ()
	return &PostAPIV3CloudProvidersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV3CloudProvidersParamsWithTimeout creates a new PostAPIV3CloudProvidersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIV3CloudProvidersParamsWithTimeout(timeout time.Duration) *PostAPIV3CloudProvidersParams {
	var ()
	return &PostAPIV3CloudProvidersParams{

		timeout: timeout,
	}
}

// NewPostAPIV3CloudProvidersParamsWithContext creates a new PostAPIV3CloudProvidersParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIV3CloudProvidersParamsWithContext(ctx context.Context) *PostAPIV3CloudProvidersParams {
	var ()
	return &PostAPIV3CloudProvidersParams{

		Context: ctx,
	}
}

// NewPostAPIV3CloudProvidersParamsWithHTTPClient creates a new PostAPIV3CloudProvidersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIV3CloudProvidersParamsWithHTTPClient(client *http.Client) *PostAPIV3CloudProvidersParams {
	var ()
	return &PostAPIV3CloudProvidersParams{
		HTTPClient: client,
	}
}

/*PostAPIV3CloudProvidersParams contains all the parameters to send to the API endpoint
for the post Api v3 cloud providers operation typically these are written to a http.Request
*/
type PostAPIV3CloudProvidersParams struct {

	/*Apidocs
	  Link to API documentation for this Cloud Provider

	*/
	Apidocs *string
	/*Config
	  Cloud Provider configuration

	*/
	Config string
	/*Description
	  Cloud Provider description

	*/
	Description *string
	/*Name
	  Cloud Provider name

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) WithTimeout(timeout time.Duration) *PostAPIV3CloudProvidersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) WithContext(ctx context.Context) *PostAPIV3CloudProvidersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) WithHTTPClient(client *http.Client) *PostAPIV3CloudProvidersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithApidocs adds the apidocs to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) WithApidocs(apidocs *string) *PostAPIV3CloudProvidersParams {
	o.SetApidocs(apidocs)
	return o
}

// SetApidocs adds the apidocs to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) SetApidocs(apidocs *string) {
	o.Apidocs = apidocs
}

// WithConfig adds the config to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) WithConfig(config string) *PostAPIV3CloudProvidersParams {
	o.SetConfig(config)
	return o
}

// SetConfig adds the config to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) SetConfig(config string) {
	o.Config = config
}

// WithDescription adds the description to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) WithDescription(description *string) *PostAPIV3CloudProvidersParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) SetDescription(description *string) {
	o.Description = description
}

// WithName adds the name to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) WithName(name string) *PostAPIV3CloudProvidersParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the post Api v3 cloud providers params
func (o *PostAPIV3CloudProvidersParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV3CloudProvidersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Apidocs != nil {

		// form param apidocs
		var frApidocs string
		if o.Apidocs != nil {
			frApidocs = *o.Apidocs
		}
		fApidocs := frApidocs
		if fApidocs != "" {
			if err := r.SetFormParam("apidocs", fApidocs); err != nil {
				return err
			}
		}

	}

	// form param config
	frConfig := o.Config
	fConfig := frConfig
	if fConfig != "" {
		if err := r.SetFormParam("config", fConfig); err != nil {
			return err
		}
	}

	if o.Description != nil {

		// form param description
		var frDescription string
		if o.Description != nil {
			frDescription = *o.Description
		}
		fDescription := frDescription
		if fDescription != "" {
			if err := r.SetFormParam("description", fDescription); err != nil {
				return err
			}
		}

	}

	// form param name
	frName := o.Name
	fName := frName
	if fName != "" {
		if err := r.SetFormParam("name", fName); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
