// Code generated by go-swagger; DO NOT EDIT.

package locations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// GetAPIV3LocationsLevelsReader is a Reader for the GetAPIV3LocationsLevels structure.
type GetAPIV3LocationsLevelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3LocationsLevelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV3LocationsLevelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV3LocationsLevelsOK creates a GetAPIV3LocationsLevelsOK with default headers values
func NewGetAPIV3LocationsLevelsOK() *GetAPIV3LocationsLevelsOK {
	return &GetAPIV3LocationsLevelsOK{}
}

/*GetAPIV3LocationsLevelsOK handles this case with default header values.

Get a list of all location levels, possibly filtered
*/
type GetAPIV3LocationsLevelsOK struct {
	Payload models.GetAPIV3LocationsLevelsOKBody
}

func (o *GetAPIV3LocationsLevelsOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/locations/levels][%d] getApiV3LocationsLevelsOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3LocationsLevelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
