// Code generated by go-swagger; DO NOT EDIT.

package locations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAPIV3LocationsRootsParams creates a new GetAPIV3LocationsRootsParams object
// with the default values initialized.
func NewGetAPIV3LocationsRootsParams() *GetAPIV3LocationsRootsParams {

	return &GetAPIV3LocationsRootsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV3LocationsRootsParamsWithTimeout creates a new GetAPIV3LocationsRootsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV3LocationsRootsParamsWithTimeout(timeout time.Duration) *GetAPIV3LocationsRootsParams {

	return &GetAPIV3LocationsRootsParams{

		timeout: timeout,
	}
}

// NewGetAPIV3LocationsRootsParamsWithContext creates a new GetAPIV3LocationsRootsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV3LocationsRootsParamsWithContext(ctx context.Context) *GetAPIV3LocationsRootsParams {

	return &GetAPIV3LocationsRootsParams{

		Context: ctx,
	}
}

// NewGetAPIV3LocationsRootsParamsWithHTTPClient creates a new GetAPIV3LocationsRootsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV3LocationsRootsParamsWithHTTPClient(client *http.Client) *GetAPIV3LocationsRootsParams {

	return &GetAPIV3LocationsRootsParams{
		HTTPClient: client,
	}
}

/*GetAPIV3LocationsRootsParams contains all the parameters to send to the API endpoint
for the get Api v3 locations roots operation typically these are written to a http.Request
*/
type GetAPIV3LocationsRootsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get Api v3 locations roots params
func (o *GetAPIV3LocationsRootsParams) WithTimeout(timeout time.Duration) *GetAPIV3LocationsRootsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Api v3 locations roots params
func (o *GetAPIV3LocationsRootsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Api v3 locations roots params
func (o *GetAPIV3LocationsRootsParams) WithContext(ctx context.Context) *GetAPIV3LocationsRootsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Api v3 locations roots params
func (o *GetAPIV3LocationsRootsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get Api v3 locations roots params
func (o *GetAPIV3LocationsRootsParams) WithHTTPClient(client *http.Client) *GetAPIV3LocationsRootsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get Api v3 locations roots params
func (o *GetAPIV3LocationsRootsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV3LocationsRootsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
