// Code generated by go-swagger; DO NOT EDIT.

package locations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// GetAPIV3LocationsReader is a Reader for the GetAPIV3Locations structure.
type GetAPIV3LocationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3LocationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV3LocationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV3LocationsOK creates a GetAPIV3LocationsOK with default headers values
func NewGetAPIV3LocationsOK() *GetAPIV3LocationsOK {
	return &GetAPIV3LocationsOK{}
}

/*GetAPIV3LocationsOK handles this case with default header values.

Return a list of locations, possibly filtered
*/
type GetAPIV3LocationsOK struct {
	Payload models.GetAPIV3LocationsOKBody
}

func (o *GetAPIV3LocationsOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/locations][%d] getApiV3LocationsOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3LocationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
