// Code generated by go-swagger; DO NOT EDIT.

package locations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAPIV3LocationsParams creates a new GetAPIV3LocationsParams object
// with the default values initialized.
func NewGetAPIV3LocationsParams() *GetAPIV3LocationsParams {

	return &GetAPIV3LocationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV3LocationsParamsWithTimeout creates a new GetAPIV3LocationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV3LocationsParamsWithTimeout(timeout time.Duration) *GetAPIV3LocationsParams {

	return &GetAPIV3LocationsParams{

		timeout: timeout,
	}
}

// NewGetAPIV3LocationsParamsWithContext creates a new GetAPIV3LocationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV3LocationsParamsWithContext(ctx context.Context) *GetAPIV3LocationsParams {

	return &GetAPIV3LocationsParams{

		Context: ctx,
	}
}

// NewGetAPIV3LocationsParamsWithHTTPClient creates a new GetAPIV3LocationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV3LocationsParamsWithHTTPClient(client *http.Client) *GetAPIV3LocationsParams {

	return &GetAPIV3LocationsParams{
		HTTPClient: client,
	}
}

/*GetAPIV3LocationsParams contains all the parameters to send to the API endpoint
for the get Api v3 locations operation typically these are written to a http.Request
*/
type GetAPIV3LocationsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get Api v3 locations params
func (o *GetAPIV3LocationsParams) WithTimeout(timeout time.Duration) *GetAPIV3LocationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Api v3 locations params
func (o *GetAPIV3LocationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Api v3 locations params
func (o *GetAPIV3LocationsParams) WithContext(ctx context.Context) *GetAPIV3LocationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Api v3 locations params
func (o *GetAPIV3LocationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get Api v3 locations params
func (o *GetAPIV3LocationsParams) WithHTTPClient(client *http.Client) *GetAPIV3LocationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get Api v3 locations params
func (o *GetAPIV3LocationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV3LocationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
