// Code generated by go-swagger; DO NOT EDIT.

package locations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostAPIV3LocationsIDIDParams creates a new PostAPIV3LocationsIDIDParams object
// with the default values initialized.
func NewPostAPIV3LocationsIDIDParams() *PostAPIV3LocationsIDIDParams {
	var ()
	return &PostAPIV3LocationsIDIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV3LocationsIDIDParamsWithTimeout creates a new PostAPIV3LocationsIDIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIV3LocationsIDIDParamsWithTimeout(timeout time.Duration) *PostAPIV3LocationsIDIDParams {
	var ()
	return &PostAPIV3LocationsIDIDParams{

		timeout: timeout,
	}
}

// NewPostAPIV3LocationsIDIDParamsWithContext creates a new PostAPIV3LocationsIDIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIV3LocationsIDIDParamsWithContext(ctx context.Context) *PostAPIV3LocationsIDIDParams {
	var ()
	return &PostAPIV3LocationsIDIDParams{

		Context: ctx,
	}
}

// NewPostAPIV3LocationsIDIDParamsWithHTTPClient creates a new PostAPIV3LocationsIDIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIV3LocationsIDIDParamsWithHTTPClient(client *http.Client) *PostAPIV3LocationsIDIDParams {
	var ()
	return &PostAPIV3LocationsIDIDParams{
		HTTPClient: client,
	}
}

/*PostAPIV3LocationsIDIDParams contains all the parameters to send to the API endpoint
for the post Api v3 locations Id Id operation typically these are written to a http.Request
*/
type PostAPIV3LocationsIDIDParams struct {

	/*Description
	  Description

	*/
	Description *string
	/*ID*/
	ID int32
	/*Level
	  Location level

	*/
	Level string
	/*Name
	  Name

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post Api v3 locations Id Id params
func (o *PostAPIV3LocationsIDIDParams) WithTimeout(timeout time.Duration) *PostAPIV3LocationsIDIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post Api v3 locations Id Id params
func (o *PostAPIV3LocationsIDIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post Api v3 locations Id Id params
func (o *PostAPIV3LocationsIDIDParams) WithContext(ctx context.Context) *PostAPIV3LocationsIDIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post Api v3 locations Id Id params
func (o *PostAPIV3LocationsIDIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post Api v3 locations Id Id params
func (o *PostAPIV3LocationsIDIDParams) WithHTTPClient(client *http.Client) *PostAPIV3LocationsIDIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post Api v3 locations Id Id params
func (o *PostAPIV3LocationsIDIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDescription adds the description to the post Api v3 locations Id Id params
func (o *PostAPIV3LocationsIDIDParams) WithDescription(description *string) *PostAPIV3LocationsIDIDParams {
	o.SetDescription(description)
	return o
}

// SetDescription adds the description to the post Api v3 locations Id Id params
func (o *PostAPIV3LocationsIDIDParams) SetDescription(description *string) {
	o.Description = description
}

// WithID adds the id to the post Api v3 locations Id Id params
func (o *PostAPIV3LocationsIDIDParams) WithID(id int32) *PostAPIV3LocationsIDIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post Api v3 locations Id Id params
func (o *PostAPIV3LocationsIDIDParams) SetID(id int32) {
	o.ID = id
}

// WithLevel adds the level to the post Api v3 locations Id Id params
func (o *PostAPIV3LocationsIDIDParams) WithLevel(level string) *PostAPIV3LocationsIDIDParams {
	o.SetLevel(level)
	return o
}

// SetLevel adds the level to the post Api v3 locations Id Id params
func (o *PostAPIV3LocationsIDIDParams) SetLevel(level string) {
	o.Level = level
}

// WithName adds the name to the post Api v3 locations Id Id params
func (o *PostAPIV3LocationsIDIDParams) WithName(name string) *PostAPIV3LocationsIDIDParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the post Api v3 locations Id Id params
func (o *PostAPIV3LocationsIDIDParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV3LocationsIDIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Description != nil {

		// form param description
		var frDescription string
		if o.Description != nil {
			frDescription = *o.Description
		}
		fDescription := frDescription
		if fDescription != "" {
			if err := r.SetFormParam("description", fDescription); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	// form param level
	frLevel := o.Level
	fLevel := frLevel
	if fLevel != "" {
		if err := r.SetFormParam("level", fLevel); err != nil {
			return err
		}
	}

	// form param name
	frName := o.Name
	fName := frName
	if fName != "" {
		if err := r.SetFormParam("name", fName); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
