// Code generated by go-swagger; DO NOT EDIT.

package nics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutAPIV3NicsIDParams creates a new PutAPIV3NicsIDParams object
// with the default values initialized.
func NewPutAPIV3NicsIDParams() *PutAPIV3NicsIDParams {
	var ()
	return &PutAPIV3NicsIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV3NicsIDParamsWithTimeout creates a new PutAPIV3NicsIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutAPIV3NicsIDParamsWithTimeout(timeout time.Duration) *PutAPIV3NicsIDParams {
	var ()
	return &PutAPIV3NicsIDParams{

		timeout: timeout,
	}
}

// NewPutAPIV3NicsIDParamsWithContext creates a new PutAPIV3NicsIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutAPIV3NicsIDParamsWithContext(ctx context.Context) *PutAPIV3NicsIDParams {
	var ()
	return &PutAPIV3NicsIDParams{

		Context: ctx,
	}
}

// NewPutAPIV3NicsIDParamsWithHTTPClient creates a new PutAPIV3NicsIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutAPIV3NicsIDParamsWithHTTPClient(client *http.Client) *PutAPIV3NicsIDParams {
	var ()
	return &PutAPIV3NicsIDParams{
		HTTPClient: client,
	}
}

/*PutAPIV3NicsIDParams contains all the parameters to send to the API endpoint
for the put Api v3 nics Id operation typically these are written to a http.Request
*/
type PutAPIV3NicsIDParams struct {

	/*ID*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put Api v3 nics Id params
func (o *PutAPIV3NicsIDParams) WithTimeout(timeout time.Duration) *PutAPIV3NicsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put Api v3 nics Id params
func (o *PutAPIV3NicsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put Api v3 nics Id params
func (o *PutAPIV3NicsIDParams) WithContext(ctx context.Context) *PutAPIV3NicsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put Api v3 nics Id params
func (o *PutAPIV3NicsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put Api v3 nics Id params
func (o *PutAPIV3NicsIDParams) WithHTTPClient(client *http.Client) *PutAPIV3NicsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put Api v3 nics Id params
func (o *PutAPIV3NicsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the put Api v3 nics Id params
func (o *PutAPIV3NicsIDParams) WithID(id int32) *PutAPIV3NicsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put Api v3 nics Id params
func (o *PutAPIV3NicsIDParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV3NicsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt32(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
