// Code generated by go-swagger; DO NOT EDIT.

package switches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// GetAPIV3SwitchesFqdnReader is a Reader for the GetAPIV3SwitchesFqdn structure.
type GetAPIV3SwitchesFqdnReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3SwitchesFqdnReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV3SwitchesFqdnOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV3SwitchesFqdnOK creates a GetAPIV3SwitchesFqdnOK with default headers values
func NewGetAPIV3SwitchesFqdnOK() *GetAPIV3SwitchesFqdnOK {
	return &GetAPIV3SwitchesFqdnOK{}
}

/*GetAPIV3SwitchesFqdnOK handles this case with default header values.

Get a switch by fqdn
*/
type GetAPIV3SwitchesFqdnOK struct {
	Payload *models.Switch
}

func (o *GetAPIV3SwitchesFqdnOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/switches/{fqdn}][%d] getApiV3SwitchesFqdnOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3SwitchesFqdnOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Switch)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
