// Code generated by go-swagger; DO NOT EDIT.

package switches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostAPIV3SwitchesParams creates a new PostAPIV3SwitchesParams object
// with the default values initialized.
func NewPostAPIV3SwitchesParams() *PostAPIV3SwitchesParams {
	var ()
	return &PostAPIV3SwitchesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV3SwitchesParamsWithTimeout creates a new PostAPIV3SwitchesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIV3SwitchesParamsWithTimeout(timeout time.Duration) *PostAPIV3SwitchesParams {
	var ()
	return &PostAPIV3SwitchesParams{

		timeout: timeout,
	}
}

// NewPostAPIV3SwitchesParamsWithContext creates a new PostAPIV3SwitchesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIV3SwitchesParamsWithContext(ctx context.Context) *PostAPIV3SwitchesParams {
	var ()
	return &PostAPIV3SwitchesParams{

		Context: ctx,
	}
}

// NewPostAPIV3SwitchesParamsWithHTTPClient creates a new PostAPIV3SwitchesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIV3SwitchesParamsWithHTTPClient(client *http.Client) *PostAPIV3SwitchesParams {
	var ()
	return &PostAPIV3SwitchesParams{
		HTTPClient: client,
	}
}

/*PostAPIV3SwitchesParams contains all the parameters to send to the API endpoint
for the post Api v3 switches operation typically these are written to a http.Request
*/
type PostAPIV3SwitchesParams struct {

	/*Fqdn*/
	Fqdn string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post Api v3 switches params
func (o *PostAPIV3SwitchesParams) WithTimeout(timeout time.Duration) *PostAPIV3SwitchesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post Api v3 switches params
func (o *PostAPIV3SwitchesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post Api v3 switches params
func (o *PostAPIV3SwitchesParams) WithContext(ctx context.Context) *PostAPIV3SwitchesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post Api v3 switches params
func (o *PostAPIV3SwitchesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post Api v3 switches params
func (o *PostAPIV3SwitchesParams) WithHTTPClient(client *http.Client) *PostAPIV3SwitchesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post Api v3 switches params
func (o *PostAPIV3SwitchesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFqdn adds the fqdn to the post Api v3 switches params
func (o *PostAPIV3SwitchesParams) WithFqdn(fqdn string) *PostAPIV3SwitchesParams {
	o.SetFqdn(fqdn)
	return o
}

// SetFqdn adds the fqdn to the post Api v3 switches params
func (o *PostAPIV3SwitchesParams) SetFqdn(fqdn string) {
	o.Fqdn = fqdn
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV3SwitchesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form param fqdn
	frFqdn := o.Fqdn
	fFqdn := frFqdn
	if fFqdn != "" {
		if err := r.SetFormParam("fqdn", fFqdn); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
