// Code generated by go-swagger; DO NOT EDIT.

package inventories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// GetAPIV3InventoriesReader is a Reader for the GetAPIV3Inventories structure.
type GetAPIV3InventoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3InventoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV3InventoriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV3InventoriesOK creates a GetAPIV3InventoriesOK with default headers values
func NewGetAPIV3InventoriesOK() *GetAPIV3InventoriesOK {
	return &GetAPIV3InventoriesOK{}
}

/*GetAPIV3InventoriesOK handles this case with default header values.

Return a list of inventories, possibly filtered
*/
type GetAPIV3InventoriesOK struct {
	Payload models.GetAPIV3InventoriesOKBody
}

func (o *GetAPIV3InventoriesOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/inventories][%d] getApiV3InventoriesOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3InventoriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
