// Code generated by go-swagger; DO NOT EDIT.

package inventories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAPIV3InventoriesInventoryNumberParams creates a new GetAPIV3InventoriesInventoryNumberParams object
// with the default values initialized.
func NewGetAPIV3InventoriesInventoryNumberParams() *GetAPIV3InventoriesInventoryNumberParams {
	var ()
	return &GetAPIV3InventoriesInventoryNumberParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV3InventoriesInventoryNumberParamsWithTimeout creates a new GetAPIV3InventoriesInventoryNumberParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAPIV3InventoriesInventoryNumberParamsWithTimeout(timeout time.Duration) *GetAPIV3InventoriesInventoryNumberParams {
	var ()
	return &GetAPIV3InventoriesInventoryNumberParams{

		timeout: timeout,
	}
}

// NewGetAPIV3InventoriesInventoryNumberParamsWithContext creates a new GetAPIV3InventoriesInventoryNumberParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAPIV3InventoriesInventoryNumberParamsWithContext(ctx context.Context) *GetAPIV3InventoriesInventoryNumberParams {
	var ()
	return &GetAPIV3InventoriesInventoryNumberParams{

		Context: ctx,
	}
}

// NewGetAPIV3InventoriesInventoryNumberParamsWithHTTPClient creates a new GetAPIV3InventoriesInventoryNumberParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAPIV3InventoriesInventoryNumberParamsWithHTTPClient(client *http.Client) *GetAPIV3InventoriesInventoryNumberParams {
	var ()
	return &GetAPIV3InventoriesInventoryNumberParams{
		HTTPClient: client,
	}
}

/*GetAPIV3InventoriesInventoryNumberParams contains all the parameters to send to the API endpoint
for the get Api v3 inventories inventory number operation typically these are written to a http.Request
*/
type GetAPIV3InventoriesInventoryNumberParams struct {

	/*InventoryNumber*/
	InventoryNumber string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get Api v3 inventories inventory number params
func (o *GetAPIV3InventoriesInventoryNumberParams) WithTimeout(timeout time.Duration) *GetAPIV3InventoriesInventoryNumberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Api v3 inventories inventory number params
func (o *GetAPIV3InventoriesInventoryNumberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Api v3 inventories inventory number params
func (o *GetAPIV3InventoriesInventoryNumberParams) WithContext(ctx context.Context) *GetAPIV3InventoriesInventoryNumberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Api v3 inventories inventory number params
func (o *GetAPIV3InventoriesInventoryNumberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get Api v3 inventories inventory number params
func (o *GetAPIV3InventoriesInventoryNumberParams) WithHTTPClient(client *http.Client) *GetAPIV3InventoriesInventoryNumberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get Api v3 inventories inventory number params
func (o *GetAPIV3InventoriesInventoryNumberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInventoryNumber adds the inventoryNumber to the get Api v3 inventories inventory number params
func (o *GetAPIV3InventoriesInventoryNumberParams) WithInventoryNumber(inventoryNumber string) *GetAPIV3InventoriesInventoryNumberParams {
	o.SetInventoryNumber(inventoryNumber)
	return o
}

// SetInventoryNumber adds the inventoryNumber to the get Api v3 inventories inventory number params
func (o *GetAPIV3InventoriesInventoryNumberParams) SetInventoryNumber(inventoryNumber string) {
	o.InventoryNumber = inventoryNumber
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV3InventoriesInventoryNumberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param inventory_number
	if err := r.SetPathParam("inventory_number", o.InventoryNumber); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
