// Code generated by go-swagger; DO NOT EDIT.

package inventories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// GetAPIV3InventoriesInventoryNumberAttachmentsFingerprintReader is a Reader for the GetAPIV3InventoriesInventoryNumberAttachmentsFingerprint structure.
type GetAPIV3InventoriesInventoryNumberAttachmentsFingerprintReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV3InventoriesInventoryNumberAttachmentsFingerprintReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAPIV3InventoriesInventoryNumberAttachmentsFingerprintOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAPIV3InventoriesInventoryNumberAttachmentsFingerprintOK creates a GetAPIV3InventoriesInventoryNumberAttachmentsFingerprintOK with default headers values
func NewGetAPIV3InventoriesInventoryNumberAttachmentsFingerprintOK() *GetAPIV3InventoriesInventoryNumberAttachmentsFingerprintOK {
	return &GetAPIV3InventoriesInventoryNumberAttachmentsFingerprintOK{}
}

/*GetAPIV3InventoriesInventoryNumberAttachmentsFingerprintOK handles this case with default header values.

Get an attachment
*/
type GetAPIV3InventoriesInventoryNumberAttachmentsFingerprintOK struct {
	Payload *models.Attachment
}

func (o *GetAPIV3InventoriesInventoryNumberAttachmentsFingerprintOK) Error() string {
	return fmt.Sprintf("[GET /api/v3/inventories/{inventory_number}/attachments/{fingerprint}][%d] getApiV3InventoriesInventoryNumberAttachmentsFingerprintOK  %+v", 200, o.Payload)
}

func (o *GetAPIV3InventoriesInventoryNumberAttachmentsFingerprintOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Attachment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
