// Code generated by go-swagger; DO NOT EDIT.

package inventories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"os"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostAPIV3InventoriesInventoryNumberAttachmentsParams creates a new PostAPIV3InventoriesInventoryNumberAttachmentsParams object
// with the default values initialized.
func NewPostAPIV3InventoriesInventoryNumberAttachmentsParams() *PostAPIV3InventoriesInventoryNumberAttachmentsParams {
	var ()
	return &PostAPIV3InventoriesInventoryNumberAttachmentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV3InventoriesInventoryNumberAttachmentsParamsWithTimeout creates a new PostAPIV3InventoriesInventoryNumberAttachmentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostAPIV3InventoriesInventoryNumberAttachmentsParamsWithTimeout(timeout time.Duration) *PostAPIV3InventoriesInventoryNumberAttachmentsParams {
	var ()
	return &PostAPIV3InventoriesInventoryNumberAttachmentsParams{

		timeout: timeout,
	}
}

// NewPostAPIV3InventoriesInventoryNumberAttachmentsParamsWithContext creates a new PostAPIV3InventoriesInventoryNumberAttachmentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostAPIV3InventoriesInventoryNumberAttachmentsParamsWithContext(ctx context.Context) *PostAPIV3InventoriesInventoryNumberAttachmentsParams {
	var ()
	return &PostAPIV3InventoriesInventoryNumberAttachmentsParams{

		Context: ctx,
	}
}

// NewPostAPIV3InventoriesInventoryNumberAttachmentsParamsWithHTTPClient creates a new PostAPIV3InventoriesInventoryNumberAttachmentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostAPIV3InventoriesInventoryNumberAttachmentsParamsWithHTTPClient(client *http.Client) *PostAPIV3InventoriesInventoryNumberAttachmentsParams {
	var ()
	return &PostAPIV3InventoriesInventoryNumberAttachmentsParams{
		HTTPClient: client,
	}
}

/*PostAPIV3InventoriesInventoryNumberAttachmentsParams contains all the parameters to send to the API endpoint
for the post Api v3 inventories inventory number attachments operation typically these are written to a http.Request
*/
type PostAPIV3InventoriesInventoryNumberAttachmentsParams struct {

	/*Data*/
	Data os.File
	/*InventoryNumber*/
	InventoryNumber string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post Api v3 inventories inventory number attachments params
func (o *PostAPIV3InventoriesInventoryNumberAttachmentsParams) WithTimeout(timeout time.Duration) *PostAPIV3InventoriesInventoryNumberAttachmentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post Api v3 inventories inventory number attachments params
func (o *PostAPIV3InventoriesInventoryNumberAttachmentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post Api v3 inventories inventory number attachments params
func (o *PostAPIV3InventoriesInventoryNumberAttachmentsParams) WithContext(ctx context.Context) *PostAPIV3InventoriesInventoryNumberAttachmentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post Api v3 inventories inventory number attachments params
func (o *PostAPIV3InventoriesInventoryNumberAttachmentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post Api v3 inventories inventory number attachments params
func (o *PostAPIV3InventoriesInventoryNumberAttachmentsParams) WithHTTPClient(client *http.Client) *PostAPIV3InventoriesInventoryNumberAttachmentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post Api v3 inventories inventory number attachments params
func (o *PostAPIV3InventoriesInventoryNumberAttachmentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the post Api v3 inventories inventory number attachments params
func (o *PostAPIV3InventoriesInventoryNumberAttachmentsParams) WithData(data os.File) *PostAPIV3InventoriesInventoryNumberAttachmentsParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the post Api v3 inventories inventory number attachments params
func (o *PostAPIV3InventoriesInventoryNumberAttachmentsParams) SetData(data os.File) {
	o.Data = data
}

// WithInventoryNumber adds the inventoryNumber to the post Api v3 inventories inventory number attachments params
func (o *PostAPIV3InventoriesInventoryNumberAttachmentsParams) WithInventoryNumber(inventoryNumber string) *PostAPIV3InventoriesInventoryNumberAttachmentsParams {
	o.SetInventoryNumber(inventoryNumber)
	return o
}

// SetInventoryNumber adds the inventoryNumber to the post Api v3 inventories inventory number attachments params
func (o *PostAPIV3InventoriesInventoryNumberAttachmentsParams) SetInventoryNumber(inventoryNumber string) {
	o.InventoryNumber = inventoryNumber
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV3InventoriesInventoryNumberAttachmentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form file param data
	if err := r.SetFileParam("data", &o.Data); err != nil {
		return err
	}

	// path param inventory_number
	if err := r.SetPathParam("inventory_number", o.InventoryNumber); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
