// Code generated by go-swagger; DO NOT EDIT.

package inventories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/idb-project/go-idb/models"
)

// PostAPIV3InventoriesReader is a Reader for the PostAPIV3Inventories structure.
type PostAPIV3InventoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV3InventoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewPostAPIV3InventoriesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostAPIV3InventoriesCreated creates a PostAPIV3InventoriesCreated with default headers values
func NewPostAPIV3InventoriesCreated() *PostAPIV3InventoriesCreated {
	return &PostAPIV3InventoriesCreated{}
}

/*PostAPIV3InventoriesCreated handles this case with default header values.

Create a new inventory
*/
type PostAPIV3InventoriesCreated struct {
	Payload *models.Inventory
}

func (o *PostAPIV3InventoriesCreated) Error() string {
	return fmt.Sprintf("[POST /api/v3/inventories][%d] postApiV3InventoriesCreated  %+v", 201, o.Payload)
}

func (o *PostAPIV3InventoriesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Inventory)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
