// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// IPAddress Ip address
// swagger:model IpAddress

type IPAddress struct {

	// IPv4 address
	Addr string `json:"addr,omitempty"`

	// IPv6 address
	AddrV6 string `json:"addr_v6,omitempty"`

	// family
	Family string `json:"family,omitempty"`

	// IPv4 netmask
	Netmask string `json:"netmask,omitempty"`

	// IPv6 prefix
	NetmaskV6 string `json:"netmask_v6,omitempty"`
}

/* polymorph IpAddress addr false */

/* polymorph IpAddress addr_v6 false */

/* polymorph IpAddress family false */

/* polymorph IpAddress netmask false */

/* polymorph IpAddress netmask_v6 false */

// Validate validates this Ip address
func (m *IPAddress) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *IPAddress) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IPAddress) UnmarshalBinary(b []byte) error {
	var res IPAddress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
