// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// LocationLevel Get a list of all location levels, possibly filtered
// swagger:model LocationLevel

type LocationLevel struct {

	// Description
	Description string `json:"description,omitempty"`

	// Level
	Level int32 `json:"level,omitempty"`

	// Name
	Name string `json:"name,omitempty"`
}

/* polymorph LocationLevel description false */

/* polymorph LocationLevel level false */

/* polymorph LocationLevel name false */

// Validate validates this location level
func (m *LocationLevel) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *LocationLevel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LocationLevel) UnmarshalBinary(b []byte) error {
	var res LocationLevel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
