// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Machine Searches machines with specific software configurations
// swagger:model Machine

type Machine struct {

	// Architecture
	Arch string `json:"arch,omitempty"`

	// true if the machine is updated automatically
	AutoUpdate bool `json:"auto_update,omitempty"`

	// backup brand
	BackupBrand int32 `json:"backup_brand,omitempty"`

	// Last differential backup time
	BackupLastDiffRun string `json:"backup_last_diff_run,omitempty"`

	// Last differential backup size
	BackupLastDiffSize int64 `json:"backup_last_diff_size,omitempty"`

	// Last full backup time
	BackupLastFullRun string `json:"backup_last_full_run,omitempty"`

	// Last full backup size
	BackupLastFullSize int64 `json:"backup_last_full_size,omitempty"`

	// Last incremental backup time
	BackupLastIncRun string `json:"backup_last_inc_run,omitempty"`

	// Last incremental backup size
	BackupLastIncSize int64 `json:"backup_last_inc_size,omitempty"`

	// Backup type
	BackupType int32 `json:"backup_type,omitempty"`

	// Business Criticality
	BusinessCriticality string `json:"business_criticality,omitempty"`

	// Business Notification
	BusinessNotification string `json:"business_notification,omitempty"`

	// Business purpose
	BusinessPurpose string `json:"business_purpose,omitempty"`

	// Configuration instructions
	ConfigInstructions string `json:"config_instructions,omitempty"`

	// Number of CPU cores
	Cores int32 `json:"cores,omitempty"`

	// Creation date RFC3999 formatted
	CreatedAt string `json:"created_at,omitempty"`

	// Deletion date RFC3999 formatted
	DeletedAt string `json:"deleted_at,omitempty"`

	// Description
	Description string `json:"description,omitempty"`

	// Disc space in bytes
	Diskspace int32 `json:"diskspace,omitempty"`

	// FQDN
	Fqdn string `json:"fqdn,omitempty"`

	// mrtg url
	MrtgURL string `json:"mrtg_url,omitempty"`

	// needs reboot
	NeedsReboot bool `json:"needs_reboot,omitempty"`

	// Operating system
	Os string `json:"os,omitempty"`

	// Operating system release
	OsRelease string `json:"os_release,omitempty"`

	// pending security updates
	PendingSecurityUpdates int32 `json:"pending_security_updates,omitempty"`

	// pending updates
	PendingUpdates int32 `json:"pending_updates,omitempty"`

	// pending updates package names
	PendingUpdatesPackageNames string `json:"pending_updates_package_names,omitempty"`

	// pending updates sum
	PendingUpdatesSum int32 `json:"pending_updates_sum,omitempty"`

	// Location id of power feed a
	PowerFeedA int32 `json:"power_feed_a,omitempty"`

	// Location id of power feed b
	PowerFeedB int32 `json:"power_feed_b,omitempty"`

	// Amount of RAM in MB
	RAM int32 `json:"ram,omitempty"`

	// raw data api
	RawDataAPI string `json:"raw_data_api,omitempty"`

	// raw data puppetdb
	RawDataPuppetdb string `json:"raw_data_puppetdb,omitempty"`

	// Serial number
	Serialnumber string `json:"serialnumber,omitempty"`

	// Service date RFC3999 formatted
	ServicedAt string `json:"serviced_at,omitempty"`

	// severity class
	SeverityClass string `json:"severity_class,omitempty"`

	// Known installed doftware packages
	Software []string `json:"software"`

	// Software characteristics
	SwCharacteristics string `json:"sw_characteristics,omitempty"`

	// switch url
	SwitchURL string `json:"switch_url,omitempty"`

	// ucs role
	UcsRole string `json:"ucs_role,omitempty"`

	// unattended upgrades
	UnattendedUpgrades bool `json:"unattended_upgrades,omitempty"`

	// unattended upgrades blacklisted packages
	UnattendedUpgradesBlacklistedPackages string `json:"unattended_upgrades_blacklisted_packages,omitempty"`

	// unattended upgrades reboot
	UnattendedUpgradesReboot bool `json:"unattended_upgrades_reboot,omitempty"`

	// unattended upgrades repos
	UnattendedUpgradesRepos string `json:"unattended_upgrades_repos,omitempty"`

	// unattended upgrades time
	UnattendedUpgradesTime string `json:"unattended_upgrades_time,omitempty"`

	// Update date RFC3999 formatted
	UpdatedAt string `json:"updated_at,omitempty"`

	// Uptime in seconds
	Uptime int32 `json:"uptime,omitempty"`

	// FQDN of virtual machine host if this is a virtual machine
	Vmhost string `json:"vmhost,omitempty"`
}

/* polymorph Machine arch false */

/* polymorph Machine auto_update false */

/* polymorph Machine backup_brand false */

/* polymorph Machine backup_last_diff_run false */

/* polymorph Machine backup_last_diff_size false */

/* polymorph Machine backup_last_full_run false */

/* polymorph Machine backup_last_full_size false */

/* polymorph Machine backup_last_inc_run false */

/* polymorph Machine backup_last_inc_size false */

/* polymorph Machine backup_type false */

/* polymorph Machine business_criticality false */

/* polymorph Machine business_notification false */

/* polymorph Machine business_purpose false */

/* polymorph Machine config_instructions false */

/* polymorph Machine cores false */

/* polymorph Machine created_at false */

/* polymorph Machine deleted_at false */

/* polymorph Machine description false */

/* polymorph Machine diskspace false */

/* polymorph Machine fqdn false */

/* polymorph Machine mrtg_url false */

/* polymorph Machine needs_reboot false */

/* polymorph Machine os false */

/* polymorph Machine os_release false */

/* polymorph Machine pending_security_updates false */

/* polymorph Machine pending_updates false */

/* polymorph Machine pending_updates_package_names false */

/* polymorph Machine pending_updates_sum false */

/* polymorph Machine power_feed_a false */

/* polymorph Machine power_feed_b false */

/* polymorph Machine ram false */

/* polymorph Machine raw_data_api false */

/* polymorph Machine raw_data_puppetdb false */

/* polymorph Machine serialnumber false */

/* polymorph Machine serviced_at false */

/* polymorph Machine severity_class false */

/* polymorph Machine software false */

/* polymorph Machine sw_characteristics false */

/* polymorph Machine switch_url false */

/* polymorph Machine ucs_role false */

/* polymorph Machine unattended_upgrades false */

/* polymorph Machine unattended_upgrades_blacklisted_packages false */

/* polymorph Machine unattended_upgrades_reboot false */

/* polymorph Machine unattended_upgrades_repos false */

/* polymorph Machine unattended_upgrades_time false */

/* polymorph Machine updated_at false */

/* polymorph Machine uptime false */

/* polymorph Machine vmhost false */

// Validate validates this machine
func (m *Machine) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSoftware(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Machine) validateSoftware(formats strfmt.Registry) error {

	if swag.IsZero(m.Software) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Machine) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Machine) UnmarshalBinary(b []byte) error {
	var res Machine
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
