// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PostAPIV3Inventories Create a new inventory
// swagger:model postApiV3Inventories

type PostAPIV3Inventories struct {

	// Additional category description
	Category string `json:"category,omitempty"`

	// Comment field
	Comment string `json:"comment,omitempty"`

	// Creation date RFC3999 formatted
	CreatedAt string `json:"created_at,omitempty"`

	// Deletion date RFC3999 formatted
	DeletedAt string `json:"deleted_at,omitempty"`

	// Id
	ID int32 `json:"id,omitempty"`

	// Installation date as YYYY-MM-DD
	InstallDate string `json:"install_date,omitempty"`

	// Inventory Number
	InventoryNumber string `json:"inventory_number,omitempty"`

	// Inventory status
	InventoryStatus string `json:"inventory_status,omitempty"`

	// Inventory status id
	InventoryStatusID int32 `json:"inventory_status_id,omitempty"`

	// ID of the location
	LocationID int32 `json:"location_id,omitempty"`

	// machines FQDN if this inventoy is a machine
	Machine string `json:"machine,omitempty"`

	// Name
	Name string `json:"name,omitempty"`

	// Factory part number
	PartNumber string `json:"part_number,omitempty"`

	// Additional place description
	Place string `json:"place,omitempty"`

	// Purchase date as YYYY-MM-DD
	PurchaseDate string `json:"purchase_date,omitempty"`

	// Seller
	Seller string `json:"seller,omitempty"`

	// Factory serial number
	Serial string `json:"serial,omitempty"`

	// Update date RFC3999 formatted
	UpdatedAt string `json:"updated_at,omitempty"`

	// Warranty end date as YYYY-MM-DD
	WarrantyEnd string `json:"warranty_end,omitempty"`
}

/* polymorph postApiV3Inventories category false */

/* polymorph postApiV3Inventories comment false */

/* polymorph postApiV3Inventories created_at false */

/* polymorph postApiV3Inventories deleted_at false */

/* polymorph postApiV3Inventories id false */

/* polymorph postApiV3Inventories install_date false */

/* polymorph postApiV3Inventories inventory_number false */

/* polymorph postApiV3Inventories inventory_status false */

/* polymorph postApiV3Inventories inventory_status_id false */

/* polymorph postApiV3Inventories location_id false */

/* polymorph postApiV3Inventories machine false */

/* polymorph postApiV3Inventories name false */

/* polymorph postApiV3Inventories part_number false */

/* polymorph postApiV3Inventories place false */

/* polymorph postApiV3Inventories purchase_date false */

/* polymorph postApiV3Inventories seller false */

/* polymorph postApiV3Inventories serial false */

/* polymorph postApiV3Inventories updated_at false */

/* polymorph postApiV3Inventories warranty_end false */

// Validate validates this post Api v3 inventories
func (m *PostAPIV3Inventories) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PostAPIV3Inventories) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostAPIV3Inventories) UnmarshalBinary(b []byte) error {
	var res PostAPIV3Inventories
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
