// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PostAPIV3LocationsID Create a new child location
// swagger:model postApiV3LocationsId

type PostAPIV3LocationsID struct {

	// Child location ids
	Children []int32 `json:"children"`

	// Description
	Description string `json:"description,omitempty"`

	// Location level
	Level string `json:"level,omitempty"`

	// Name
	Name string `json:"name,omitempty"`

	// Parent location id
	Parent int32 `json:"parent,omitempty"`
}

/* polymorph postApiV3LocationsId children false */

/* polymorph postApiV3LocationsId description false */

/* polymorph postApiV3LocationsId level false */

/* polymorph postApiV3LocationsId name false */

/* polymorph postApiV3LocationsId parent false */

// Validate validates this post Api v3 locations Id
func (m *PostAPIV3LocationsID) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChildren(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostAPIV3LocationsID) validateChildren(formats strfmt.Registry) error {

	if swag.IsZero(m.Children) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PostAPIV3LocationsID) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostAPIV3LocationsID) UnmarshalBinary(b []byte) error {
	var res PostAPIV3LocationsID
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
