// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PostAPIV3Machines Create a new machine
// swagger:model postApiV3Machines

type PostAPIV3Machines struct {

	// Architecture
	Arch string `json:"arch,omitempty"`

	// true if the machine is updated automatically
	AutoUpdate bool `json:"auto_update,omitempty"`

	// backup brand
	BackupBrand int32 `json:"backup_brand,omitempty"`

	// Last differential backup time
	BackupLastDiffRun string `json:"backup_last_diff_run,omitempty"`

	// Last differential backup size
	BackupLastDiffSize int64 `json:"backup_last_diff_size,omitempty"`

	// Last full backup time
	BackupLastFullRun string `json:"backup_last_full_run,omitempty"`

	// Last full backup size
	BackupLastFullSize int64 `json:"backup_last_full_size,omitempty"`

	// Last incremental backup time
	BackupLastIncRun string `json:"backup_last_inc_run,omitempty"`

	// Last incremental backup size
	BackupLastIncSize int64 `json:"backup_last_inc_size,omitempty"`

	// Backup type
	BackupType int32 `json:"backup_type,omitempty"`

	// Business Criticality
	BusinessCriticality string `json:"business_criticality,omitempty"`

	// Business Notification
	BusinessNotification string `json:"business_notification,omitempty"`

	// Business purpose
	BusinessPurpose string `json:"business_purpose,omitempty"`

	// Configuration instructions
	ConfigInstructions string `json:"config_instructions,omitempty"`

	// Number of CPU cores
	Cores int32 `json:"cores,omitempty"`

	// Creation date RFC3999 formatted
	CreatedAt string `json:"created_at,omitempty"`

	// Deletion date RFC3999 formatted
	DeletedAt string `json:"deleted_at,omitempty"`

	// Description
	Description string `json:"description,omitempty"`

	// Disc space in bytes
	Diskspace int32 `json:"diskspace,omitempty"`

	// FQDN
	Fqdn string `json:"fqdn,omitempty"`

	// mrtg url
	MrtgURL string `json:"mrtg_url,omitempty"`

	// needs reboot
	NeedsReboot bool `json:"needs_reboot,omitempty"`

	// Operating system
	Os string `json:"os,omitempty"`

	// Operating system release
	OsRelease string `json:"os_release,omitempty"`

	// pending security updates
	PendingSecurityUpdates int32 `json:"pending_security_updates,omitempty"`

	// pending updates
	PendingUpdates int32 `json:"pending_updates,omitempty"`

	// pending updates package names
	PendingUpdatesPackageNames string `json:"pending_updates_package_names,omitempty"`

	// pending updates sum
	PendingUpdatesSum int32 `json:"pending_updates_sum,omitempty"`

	// Location id of power feed a
	PowerFeedA int32 `json:"power_feed_a,omitempty"`

	// Location id of power feed b
	PowerFeedB int32 `json:"power_feed_b,omitempty"`

	// Amount of RAM in MB
	RAM int32 `json:"ram,omitempty"`

	// raw data api
	RawDataAPI string `json:"raw_data_api,omitempty"`

	// raw data puppetdb
	RawDataPuppetdb string `json:"raw_data_puppetdb,omitempty"`

	// Serial number
	Serialnumber string `json:"serialnumber,omitempty"`

	// Service date RFC3999 formatted
	ServicedAt string `json:"serviced_at,omitempty"`

	// severity class
	SeverityClass string `json:"severity_class,omitempty"`

	// software
	Software PostAPIV3MachinesSoftware `json:"software"`

	// Software characteristics
	SwCharacteristics string `json:"sw_characteristics,omitempty"`

	// switch url
	SwitchURL string `json:"switch_url,omitempty"`

	// ucs role
	UcsRole string `json:"ucs_role,omitempty"`

	// unattended upgrades
	UnattendedUpgrades bool `json:"unattended_upgrades,omitempty"`

	// unattended upgrades blacklisted packages
	UnattendedUpgradesBlacklistedPackages string `json:"unattended_upgrades_blacklisted_packages,omitempty"`

	// unattended upgrades reboot
	UnattendedUpgradesReboot bool `json:"unattended_upgrades_reboot,omitempty"`

	// unattended upgrades repos
	UnattendedUpgradesRepos string `json:"unattended_upgrades_repos,omitempty"`

	// unattended upgrades time
	UnattendedUpgradesTime string `json:"unattended_upgrades_time,omitempty"`

	// Update date RFC3999 formatted
	UpdatedAt string `json:"updated_at,omitempty"`

	// Uptime in seconds
	Uptime int32 `json:"uptime,omitempty"`

	// FQDN of virtual machine host if this is a virtual machine
	Vmhost string `json:"vmhost,omitempty"`
}

/* polymorph postApiV3Machines arch false */

/* polymorph postApiV3Machines auto_update false */

/* polymorph postApiV3Machines backup_brand false */

/* polymorph postApiV3Machines backup_last_diff_run false */

/* polymorph postApiV3Machines backup_last_diff_size false */

/* polymorph postApiV3Machines backup_last_full_run false */

/* polymorph postApiV3Machines backup_last_full_size false */

/* polymorph postApiV3Machines backup_last_inc_run false */

/* polymorph postApiV3Machines backup_last_inc_size false */

/* polymorph postApiV3Machines backup_type false */

/* polymorph postApiV3Machines business_criticality false */

/* polymorph postApiV3Machines business_notification false */

/* polymorph postApiV3Machines business_purpose false */

/* polymorph postApiV3Machines config_instructions false */

/* polymorph postApiV3Machines cores false */

/* polymorph postApiV3Machines created_at false */

/* polymorph postApiV3Machines deleted_at false */

/* polymorph postApiV3Machines description false */

/* polymorph postApiV3Machines diskspace false */

/* polymorph postApiV3Machines fqdn false */

/* polymorph postApiV3Machines mrtg_url false */

/* polymorph postApiV3Machines needs_reboot false */

/* polymorph postApiV3Machines os false */

/* polymorph postApiV3Machines os_release false */

/* polymorph postApiV3Machines pending_security_updates false */

/* polymorph postApiV3Machines pending_updates false */

/* polymorph postApiV3Machines pending_updates_package_names false */

/* polymorph postApiV3Machines pending_updates_sum false */

/* polymorph postApiV3Machines power_feed_a false */

/* polymorph postApiV3Machines power_feed_b false */

/* polymorph postApiV3Machines ram false */

/* polymorph postApiV3Machines raw_data_api false */

/* polymorph postApiV3Machines raw_data_puppetdb false */

/* polymorph postApiV3Machines serialnumber false */

/* polymorph postApiV3Machines serviced_at false */

/* polymorph postApiV3Machines severity_class false */

/* polymorph postApiV3Machines software false */

/* polymorph postApiV3Machines sw_characteristics false */

/* polymorph postApiV3Machines switch_url false */

/* polymorph postApiV3Machines ucs_role false */

/* polymorph postApiV3Machines unattended_upgrades false */

/* polymorph postApiV3Machines unattended_upgrades_blacklisted_packages false */

/* polymorph postApiV3Machines unattended_upgrades_reboot false */

/* polymorph postApiV3Machines unattended_upgrades_repos false */

/* polymorph postApiV3Machines unattended_upgrades_time false */

/* polymorph postApiV3Machines updated_at false */

/* polymorph postApiV3Machines uptime false */

/* polymorph postApiV3Machines vmhost false */

// Validate validates this post Api v3 machines
func (m *PostAPIV3Machines) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PostAPIV3Machines) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostAPIV3Machines) UnmarshalBinary(b []byte) error {
	var res PostAPIV3Machines
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
