// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PutAPIV3CloudProviders Update a single cloud provider
// swagger:model putApiV3CloudProviders

type PutAPIV3CloudProviders struct {

	// Link to API documentation for this Cloud Provider
	Apidocs string `json:"apidocs,omitempty"`

	// Cloud Provider configuration
	Config string `json:"config,omitempty"`

	// Cloud Provider description
	Description string `json:"description,omitempty"`

	// Cloud Provider name
	Name string `json:"name,omitempty"`
}

/* polymorph putApiV3CloudProviders apidocs false */

/* polymorph putApiV3CloudProviders config false */

/* polymorph putApiV3CloudProviders description false */

/* polymorph putApiV3CloudProviders name false */

// Validate validates this put Api v3 cloud providers
func (m *PutAPIV3CloudProviders) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PutAPIV3CloudProviders) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PutAPIV3CloudProviders) UnmarshalBinary(b []byte) error {
	var res PutAPIV3CloudProviders
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
